/**
 * @file mod_scintilla.cpp
 * @brief boost::python scintilla module
 * @author Simon Steele
 * @note Copyright (c) 2006-2009 Simon Steele - http://untidy.net/
 *
 * Programmers Notepad 2 : The license file (license.[txt|html]) describes 
 * the conditions under which this source may be modified / distributed.
 */
#include "stdafx.h"
#include "wrapscintilla.h"

using namespace boost::python;

BOOST_PYTHON_MODULE(scintilla)
{
	boost::python::docstring_options docstring_options(true);

class_< PNScintilla, boost::noncopyable >("Scintilla", init<extensions::IDocument*>() )
	.def("IndentLine", &PNScintilla::IndentLine)
/*++Autogenerated*/
	.add_property("Anchor", &PNScintilla::GetAnchor, &PNScintilla::SetAnchor)
	.add_property("AutoCAutoHide", &PNScintilla::AutoCGetAutoHide, &PNScintilla::AutoCSetAutoHide)
	.add_property("AutoCCancelAtStart", &PNScintilla::AutoCGetCancelAtStart, &PNScintilla::AutoCSetCancelAtStart)
	.add_property("AutoCChooseSingle", &PNScintilla::AutoCGetChooseSingle, &PNScintilla::AutoCSetChooseSingle)
	.add_property("AutoCDropRestOfWord", &PNScintilla::AutoCGetDropRestOfWord, &PNScintilla::AutoCSetDropRestOfWord)
	.add_property("AutoCIgnoreCase", &PNScintilla::AutoCGetIgnoreCase, &PNScintilla::AutoCSetIgnoreCase)
	//.add_property("AutoCMaxHeight", &PNScintilla::AutoCGetMaxHeight, &PNScintilla::AutoCSetMaxHeight)
	//.add_property("AutoCMaxWidth", &PNScintilla::AutoCGetMaxWidth, &PNScintilla::AutoCSetMaxWidth)
	.add_property("AutoCSeparator", &PNScintilla::AutoCGetSeparator, &PNScintilla::AutoCSetSeparator)
	.add_property("AutoCTypeSeparator", &PNScintilla::AutoCGetTypeSeparator, &PNScintilla::AutoCSetTypeSeparator)
	.add_property("BackSpaceUnIndents", &PNScintilla::GetBackSpaceUnIndents, &PNScintilla::SetBackSpaceUnIndents)
	.add_property("BufferedDraw", &PNScintilla::GetBufferedDraw, &PNScintilla::SetBufferedDraw)
	.add_property("CaretFore", &PNScintilla::GetCaretFore, &PNScintilla::SetCaretFore)
	.add_property("CaretLineBack", &PNScintilla::GetCaretLineBack, &PNScintilla::SetCaretLineBack)
	.add_property("CaretLineVisible", &PNScintilla::GetCaretLineVisible, &PNScintilla::SetCaretLineVisible)
	.add_property("CaretPeriod", &PNScintilla::GetCaretPeriod, &PNScintilla::SetCaretPeriod)
	.add_property("CaretSticky", &PNScintilla::GetCaretSticky, &PNScintilla::SetCaretSticky)
	.add_property("CaretWidth", &PNScintilla::GetCaretWidth, &PNScintilla::SetCaretWidth)
	.add_property("CodePage", &PNScintilla::GetCodePage, &PNScintilla::SetCodePage)
	.add_property("Column", &PNScintilla::GetColumn)
	.add_property("ControlCharSymbol", &PNScintilla::GetControlCharSymbol, &PNScintilla::SetControlCharSymbol)
	.add_property("CurrentPos", &PNScintilla::GetCurrentPos, &PNScintilla::SetCurrentPos)
	.add_property("Cursor", &PNScintilla::GetCursor, &PNScintilla::SetCursor)
	.add_property("DirectFunction", &PNScintilla::GetDirectFunction)
	.add_property("DirectPointer", &PNScintilla::GetDirectPointer)
	.add_property("DocPointer", &PNScintilla::GetDocPointer, &PNScintilla::SetDocPointer)
	.add_property("EOLMode", &PNScintilla::GetEOLMode, &PNScintilla::SetEOLMode)
	.add_property("EdgeColour", &PNScintilla::GetEdgeColour, &PNScintilla::SetEdgeColour)
	.add_property("EdgeColumn", &PNScintilla::GetEdgeColumn, &PNScintilla::SetEdgeColumn)
	.add_property("EdgeMode", &PNScintilla::GetEdgeMode, &PNScintilla::SetEdgeMode)
	.add_property("EndAtLastLine", &PNScintilla::GetEndAtLastLine, &PNScintilla::SetEndAtLastLine)
	.add_property("EndStyled", &PNScintilla::GetEndStyled)
	.add_property("FirstVisibleLine", &PNScintilla::GetFirstVisibleLine)
	.add_property("Focus", &PNScintilla::GetFocus, &PNScintilla::SetEditorFocus)
	.add_property("HScrollBar", &PNScintilla::GetHScrollBar, &PNScintilla::SetHScrollBar)
	.add_property("HighlightGuide", &PNScintilla::GetHighlightGuide, &PNScintilla::SetHighlightGuide)
	.add_property("Indent", &PNScintilla::GetIndent, &PNScintilla::SetIndent)
	.add_property("IndentationGuides", &PNScintilla::GetIndentationGuides, &PNScintilla::SetIndentationGuides)
	.add_property("LastChild", &PNScintilla::GetLastChild)
	.add_property("LayoutCache", &PNScintilla::GetLayoutCache, &PNScintilla::SetLayoutCache)
	.add_property("Length", &PNScintilla::GetLength)
	.add_property("Lexer", &PNScintilla::GetLexer, &PNScintilla::SetLexer)
	.add_property("LineCount", &PNScintilla::GetLineCount)
	.add_property("LinesOnScreen", &PNScintilla::LinesOnScreen)
	.add_property("MarginLeft", &PNScintilla::GetMarginLeft, &PNScintilla::SetMarginLeft)
	.add_property("MarginMaskN", &PNScintilla::GetMarginMaskN, &PNScintilla::SetMarginMaskN)
	.add_property("MarginRight", &PNScintilla::GetMarginRight, &PNScintilla::SetMarginRight)
	.add_property("MarginSensitiveN", &PNScintilla::GetMarginSensitiveN, &PNScintilla::SetMarginSensitiveN)
	.add_property("MarginTypeN", &PNScintilla::GetMarginTypeN, &PNScintilla::SetMarginTypeN)
	.add_property("MarginWidthN", &PNScintilla::GetMarginWidthN, &PNScintilla::SetMarginWidthN)
	.add_property("MaxLineState", &PNScintilla::GetMaxLineState)
	.add_property("ModEventMask", &PNScintilla::GetModEventMask, &PNScintilla::SetModEventMask)
	.add_property("Modify", &PNScintilla::GetModify)
	.add_property("MouseDownCaptures", &PNScintilla::GetMouseDownCaptures, &PNScintilla::SetMouseDownCaptures)
	.add_property("MouseDwellTime", &PNScintilla::GetMouseDwellTime, &PNScintilla::SetMouseDwellTime)
	.add_property("Overtype", &PNScintilla::GetOvertype, &PNScintilla::SetOvertype)
	.add_property("PrintColourMode", &PNScintilla::GetPrintColourMode, &PNScintilla::SetPrintColourMode)
	.add_property("PrintMagnification", &PNScintilla::GetPrintMagnification, &PNScintilla::SetPrintMagnification)
	.add_property("PrintWrapMode", &PNScintilla::GetPrintWrapMode, &PNScintilla::SetPrintWrapMode)
	.add_property("ReadOnly", &PNScintilla::GetReadOnly, &PNScintilla::SetReadOnly)
	.add_property("ScrollWidth", &PNScintilla::GetScrollWidth, &PNScintilla::SetScrollWidth)
	.add_property("SearchFlags", &PNScintilla::GetSearchFlags, &PNScintilla::SetSearchFlags)
	.add_property("SelectionEnd", &PNScintilla::GetSelectionEnd, &PNScintilla::SetSelectionEnd)
	.add_property("SelectionIsRectangle", &PNScintilla::SelectionIsRectangle)
	.add_property("SelectionMode", &PNScintilla::GetSelectionMode, &PNScintilla::SetSelectionMode)
	.add_property("SelectionStart", &PNScintilla::GetSelectionStart, &PNScintilla::SetSelectionStart)
	.add_property("SelectionCount", &PNScintilla::GetSelections)
	.add_property("SelText", &PNScintilla::GetSelTextAsString)
	.add_property("Status", &PNScintilla::GetStatus, &PNScintilla::SetStatus)
	.add_property("StyleBits", &PNScintilla::GetStyleBits, &PNScintilla::SetStyleBits)
	.add_property("TabIndents", &PNScintilla::GetTabIndents, &PNScintilla::SetTabIndents)
	.add_property("TabWidth", &PNScintilla::GetTabWidth, &PNScintilla::SetTabWidth)
	.add_property("TargetEnd", &PNScintilla::GetTargetEnd, &PNScintilla::SetTargetEnd)
	.add_property("TargetStart", &PNScintilla::GetTargetStart, &PNScintilla::SetTargetStart)
	.add_property("TextLength", &PNScintilla::GetTextLength)
	.add_property("TwoPhaseDraw", &PNScintilla::GetTwoPhaseDraw, &PNScintilla::SetTwoPhaseDraw)
	.add_property("UndoCollection", &PNScintilla::GetUndoCollection, &PNScintilla::SetUndoCollection)
	.add_property("UsePalette", &PNScintilla::GetUsePalette, &PNScintilla::SetUsePalette)
	.add_property("UseTabs", &PNScintilla::GetUseTabs, &PNScintilla::SetUseTabs)
	.add_property("VScrollBar", &PNScintilla::GetVScrollBar, &PNScintilla::SetVScrollBar)
	.add_property("ViewEOL", &PNScintilla::GetViewEOL, &PNScintilla::SetViewEOL)
	.add_property("ViewWS", &PNScintilla::GetViewWS, &PNScintilla::SetViewWS)
	.add_property("WrapMode", &PNScintilla::GetWrapMode, &PNScintilla::SetWrapMode)
	//.add_property("WrapStartIndent", &PNScintilla::GetWrapStartIndent, &PNScintilla::SetWrapStartIndent)
	//.add_property("WrapVisualFlags", &PNScintilla::GetWrapVisualFlags, &PNScintilla::SetWrapVisualFlags)
	//.add_property("WrapVisualFlagsLocation", &PNScintilla::GetWrapVisualFlagsLocation, &PNScintilla::SetWrapVisualFlagsLocation)
	.add_property("XOffset", &PNScintilla::GetXOffset, &PNScintilla::SetXOffset)
	.add_property("Zoom", &PNScintilla::GetZoom, &PNScintilla::SetZoom)

	.add_property("RectangularSelectionCaret", &PNScintilla::GetRectangularSelectionCaret, &PNScintilla::SetRectangularSelectionCaret)
	.add_property("RectangularSelectionCaretVirtualSpace", &PNScintilla::GetRectangularSelectionCaretVirtualSpace, &PNScintilla::SetRectangularSelectionCaretVirtualSpace)
	.add_property("RectangularSelectionAnchor", &PNScintilla::GetRectangularSelectionAnchor, &PNScintilla::SetRectangularSelectionAnchor)
	.add_property("RectangularSelectionAnchorVirtualSpace", &PNScintilla::GetRectangularSelectionAnchorVirtualSpace, &PNScintilla::SetRectangularSelectionAnchorVirtualSpace)

	.add_property("AdditionalSelAlpha", &PNScintilla::GetAdditionalSelAlpha, &PNScintilla::SetAdditionalSelAlpha)
	.add_property("AdditionalCaretFore", &PNScintilla::GetAdditionalCaretFore, &PNScintilla::SetAdditionalCaretFore)
	.add_property("AdditionalCaretsBlink", &PNScintilla::GetAdditionalCaretsBlink, &PNScintilla::SetAdditionalCaretsBlink)

	.add_property("MainSelection", &PNScintilla::GetMainSelection, &PNScintilla::SetMainSelection)

	.def("AddRefDocument", &PNScintilla::AddRefDocument)
	.def("AddStyledText", &PNScintilla::AddStyledText)
	.def("AddText", &PNScintilla::AddText)
	.def("Allocate", &PNScintilla::Allocate)
	.def("AppendText", &PNScintilla::AppendText)
	.def("AssignCmdKey", &PNScintilla::AssignCmdKey)
	.def("AutoCActive", &PNScintilla::AutoCActive)
	.def("AutoCCancel", &PNScintilla::AutoCCancel)
	.def("AutoCComplete", &PNScintilla::AutoCComplete)
	.def("AutoCGetCurrent", &PNScintilla::AutoCGetCurrent)
	.def("AutoCPosStart", &PNScintilla::AutoCPosStart)
	.def("AutoCSelect", &PNScintilla::AutoCSelect)
	.def("AutoCSetFillUps", &PNScintilla::AutoCSetFillUps)
	.def("AutoCShow", &PNScintilla::AutoCShow)
	.def("AutoCStops", &PNScintilla::AutoCStops)
	.def("BackTab", &PNScintilla::BackTab)
	.def("BeginOverwriteTarget", &PNScintilla::BeginOverwriteTarget)
	.def("BeginUndoAction", &PNScintilla::BeginUndoAction)
	.def("BraceBadLight", &PNScintilla::BraceBadLight)
	.def("BraceHighlight", &PNScintilla::BraceHighlight)
	.def("BraceMatch", &PNScintilla::BraceMatch)
	.def("CallTipActive", &PNScintilla::CallTipActive)
	.def("CallTipCancel", &PNScintilla::CallTipCancel)
	.def("CallTipPosStart", &PNScintilla::CallTipPosStart)
	.def("CallTipSetHlt", &PNScintilla::CallTipSetHlt)
	.def("CallTipSetBack", &PNScintilla::CallTipSetBack)
	.def("CallTipSetFore", &PNScintilla::CallTipSetFore)
	.def("CallTipSetForeHlt", &PNScintilla::CallTipSetForeHlt)
	.def("CallTipShow", &PNScintilla::CallTipShow)
	.def("CanPaste", &PNScintilla::CanPaste)
	.def("CanRedo", &PNScintilla::CanRedo)
	.def("CanUndo", &PNScintilla::CanUndo)
	.def("Cancel", &PNScintilla::Cancel)
	.def("CharLeft", &PNScintilla::CharLeft)
	.def("CharLeftExtend", &PNScintilla::CharLeftExtend)
	.def("CharLeftRectExtend", &PNScintilla::CharLeftRectExtend)
	.def("CharRight", &PNScintilla::CharRight)
	.def("CharRightExtend", &PNScintilla::CharRightExtend)
	.def("CharRightRectExtend", &PNScintilla::CharRightRectExtend)
	.def("ChooseCaretX", &PNScintilla::ChooseCaretX)
	.def("Clear", &PNScintilla::Clear)
	.def("ClearAll", &PNScintilla::ClearAll)
	.def("ClearAllCmdKeys", &PNScintilla::ClearAllCmdKeys)
	.def("ClearCmdKey", &PNScintilla::ClearCmdKey)
	.def("ClearDocumentStyle", &PNScintilla::ClearDocumentStyle)
	.def("ClearRegisteredImages", &PNScintilla::ClearRegisteredImages)
	.def("Colourise", &PNScintilla::Colourise)
	.def("ConvertEOLs", &PNScintilla::ConvertEOLs)
	.def("Copy", &PNScintilla::Copy)
	.def("CopyRange", &PNScintilla::CopyRange)
	.def("CopyText", &PNScintilla::CopyText)
	.def("CreateDocument", &PNScintilla::CreateDocument)
	.def("Cut", &PNScintilla::Cut)
	.def("DelLineLeft", &PNScintilla::DelLineLeft)
	.def("DelLineRight", &PNScintilla::DelLineRight)
	.def("DelWordLeft", &PNScintilla::DelWordLeft)
	.def("DelWordRight", &PNScintilla::DelWordRight)
	.def("DeleteBack", &PNScintilla::DeleteBack)
	.def("DeleteBackNotLine", &PNScintilla::DeleteBackNotLine)
	.def("DocLineFromVisible", &PNScintilla::DocLineFromVisible)
	.def("DocumentEnd", &PNScintilla::DocumentEnd)
	.def("DocumentEndExtend", &PNScintilla::DocumentEndExtend)
	.def("DocumentStart", &PNScintilla::DocumentStart)
	.def("DocumentStartExtend", &PNScintilla::DocumentStartExtend)
	.def("EditToggleOvertype", &PNScintilla::EditToggleOvertype)
	.def("EmptyUndoBuffer", &PNScintilla::EmptyUndoBuffer)
	//.def("EncodedFromUTF8", &PNScintilla::EncodedFromUTF8)
	.def("EndUndoAction", &PNScintilla::EndUndoAction)
	.def("EnsureVisible", &PNScintilla::EnsureVisible)
	.def("EnsureVisibleEnforcePolicy", &PNScintilla::EnsureVisibleEnforcePolicy)
	.def("FindColumn", &PNScintilla::FindColumn)
	.def("FindText", &PNScintilla::FindTextString)
	.def("FormFeed", &PNScintilla::FormFeed)
	.def("FormatRange", &PNScintilla::FormatRange)
	.def("GetCharAt", &PNScintilla::GetCharAt)
	.def("GetCurLine", &PNScintilla::GetCurLineAsString)
	.def("GetFoldExpanded", &PNScintilla::GetFoldExpanded)
	.def("GetFoldLevel", &PNScintilla::GetFoldLevel)
	.def("GetFoldParent", &PNScintilla::GetFoldParent)
	.def("GetLine", &PNScintilla::GetLineAsString)
	.def("GetLineIndentation", &PNScintilla::GetLineIndentation)
	.def("GetLineSelEndPosition", &PNScintilla::GetLineSelEndPosition)
	.def("GetLineSelStartPosition", &PNScintilla::GetLineSelStartPosition)
	.def("GetLineEndPosition", &PNScintilla::GetLineEndPosition)
	.def("GetLineIndentPosition", &PNScintilla::GetLineIndentPosition)
	.def("GetLineState", &PNScintilla::GetLineState)
	.def("GetLineVisible", &PNScintilla::GetLineVisible)
	//.def("GetProperty", &PNScintilla::GetProperty)
	.def("GetPropertyInt", &PNScintilla::GetPropertyInt)
	//.def("GetPropertyExpanded", &PNScintilla::GetPropertyExpanded)
	//.def("GetSelText", &PNScintilla::GetSelText)
	.def("GetStyleAt", &PNScintilla::GetStyleAt)
	.def("GetStyledText", &PNScintilla::GetStyledText)
	.def("GetText", &PNScintilla::GetTextAsString, "Get n characters from the document text")
	.def("GetTextRange", &PNScintilla::GetTextRangeAsString)
	.def("GotoLine", &PNScintilla::GotoLine)
	.def("GotoPos", &PNScintilla::GotoPos)
	.def("GrabFocus", &PNScintilla::GrabFocus)
	.def("HideLines", &PNScintilla::HideLines)
	.def("HideSelection", &PNScintilla::HideSelection)
	.def("Home", &PNScintilla::Home)
	.def("HomeDisplay", &PNScintilla::HomeDisplay)
	.def("HomeDisplayExtend", &PNScintilla::HomeDisplayExtend)
	.def("HomeExtend", &PNScintilla::HomeExtend)
	.def("HomeRectExtend", &PNScintilla::HomeRectExtend)
	.def("HomeWrap", &PNScintilla::HomeWrap)
	.def("HomeWrapExtend", &PNScintilla::HomeWrapExtend)
	.def("IndicGetFore", &PNScintilla::IndicGetFore)
	.def("IndicSetFore", &PNScintilla::IndicSetFore)
	.def("IndicGetStyle", &PNScintilla::IndicGetStyle)
	.def("IndicSetStyle", &PNScintilla::IndicSetStyle)
	.def("InsertClip", &PNScintilla::InsertClip)
	.def("InsertText", &PNScintilla::InsertText)
	.def("LineCopy", &PNScintilla::LineCopy)
	.def("LineCut", &PNScintilla::LineCut)
	.def("LineDelete", &PNScintilla::LineDelete)
	.def("LineDown", &PNScintilla::LineDown)
	.def("LineDownExtend", &PNScintilla::LineDownExtend)
	.def("LineDownRectExtend", &PNScintilla::LineDownRectExtend)
	.def("LineDuplicate", &PNScintilla::LineDuplicate)
	.def("LineEnd", &PNScintilla::LineEnd)
	.def("LineEndDisplay", &PNScintilla::LineEndDisplay)
	.def("LineEndDisplayExtend", &PNScintilla::LineEndDisplayExtend)
	.def("LineEndExtend", &PNScintilla::LineEndExtend)
	.def("LineEndRectExtend", &PNScintilla::LineEndRectExtend)
	.def("LineEndWrap", &PNScintilla::LineEndWrap)
	.def("LineEndWrapExtend", &PNScintilla::LineEndWrapExtend)
	.def("LineFromPosition", &PNScintilla::LineFromPosition)
	.def("LineLength", &PNScintilla::LineLength)
	.def("LineScroll", &PNScintilla::LineScroll)
	.def("LineScrollDown", &PNScintilla::LineScrollDown)
	.def("LineScrollUp", &PNScintilla::LineScrollUp)
	.def("LineTranspose", &PNScintilla::LineTranspose)
	.def("LineUp", &PNScintilla::LineUp)
	.def("LineUpExtend", &PNScintilla::LineUpExtend)
	.def("LineUpRectExtend", &PNScintilla::LineUpRectExtend)
	.def("LinesJoin", &PNScintilla::LinesJoin)
	.def("LinesSplit", &PNScintilla::LinesSplit)
	.def("LoadLexerLibrary", &PNScintilla::LoadLexerLibrary)
	.def("LowerCase", &PNScintilla::LowerCase)
	.def("MarkerAdd", &PNScintilla::MarkerAdd)
	.def("MarkerDefine", &PNScintilla::MarkerDefine)
	.def("MarkerDefinePixmap", &PNScintilla::MarkerDefinePixmap)
	.def("MarkerDelete", &PNScintilla::MarkerDelete)
	.def("MarkerDeleteAll", &PNScintilla::MarkerDeleteAll)
	.def("MarkerDeleteHandle", &PNScintilla::MarkerDeleteHandle)
	.def("MarkerGet", &PNScintilla::MarkerGet)
	.def("MarkerLineFromHandle", &PNScintilla::MarkerLineFromHandle)
	.def("MarkerNext", &PNScintilla::MarkerNext)
	.def("MarkerPrevious", &PNScintilla::MarkerPrevious)
	.def("MarkerSetBack", &PNScintilla::MarkerSetBack)
	.def("MarkerSetFore", &PNScintilla::MarkerSetFore)
	.def("MoveCaretInsideView", &PNScintilla::MoveCaretInsideView)
	.def("NewLine", &PNScintilla::NewLine)
	//.def("Null", &PNScintilla::Null)
	.def("PageDown", &PNScintilla::PageDown)
	.def("PageDownExtend", &PNScintilla::PageDownExtend)
	.def("PageDownRectExtend", &PNScintilla::PageDownRectExtend)
	.def("PageUp", &PNScintilla::PageUp)
	.def("PageUpExtend", &PNScintilla::PageUpExtend)
	.def("PageUpRectExtend", &PNScintilla::PageUpRectExtend)
	.def("ParaDown", &PNScintilla::ParaDown)
	.def("ParaDownExtend", &PNScintilla::ParaDownExtend)
	.def("ParaUp", &PNScintilla::ParaUp)
	.def("ParaUpExtend", &PNScintilla::ParaUpExtend)
	.def("Paste", &PNScintilla::Paste)
	.def("PointXFromPosition", &PNScintilla::PointXFromPosition)
	.def("PointYFromPosition", &PNScintilla::PointYFromPosition)
	.def("PositionAfter", &PNScintilla::PositionAfter)
	.def("PositionBefore", &PNScintilla::PositionBefore)
	.def("PositionFromLine", &PNScintilla::PositionFromLine)
	.def("PositionFromPoint", &PNScintilla::PositionFromPoint)
	.def("PositionFromPointClose", &PNScintilla::PositionFromPointClose)
	.def("Redo", &PNScintilla::Redo)
	.def("RegisterImage", &PNScintilla::RegisterImage)
	.def("ReleaseDocument", &PNScintilla::ReleaseDocument)
	.def("ReplaceSel", &PNScintilla::ReplaceSel)
	.def("ReplaceTarget", &PNScintilla::ReplaceTarget)
	.def("ReplaceTargetRE", &PNScintilla::ReplaceTargetRE)
	.def("ScrollCaret", &PNScintilla::ScrollCaret)
	.def("SearchAnchor", &PNScintilla::SearchAnchor)
	.def("SearchInTarget", &PNScintilla::SearchInTarget)
	.def("SearchNext", &PNScintilla::SearchNext)
	.def("SearchPrev", &PNScintilla::SearchPrev)
	.def("SelectAll", &PNScintilla::SelectAll)
	.def("SetCharsDefault", &PNScintilla::SetCharsDefault)
	.def("SetFocus", &PNScintilla::SetFocus)
	.def("SetFoldExpanded", &PNScintilla::SetFoldExpanded)
	.def("SetFoldFlags", &PNScintilla::SetFoldFlags)
	.def("SetFoldLevel", &PNScintilla::SetFoldLevel)
	.def("SetFoldMarginColour", &PNScintilla::SetFoldMarginColour)
	.def("SetFoldMarginHiColour", &PNScintilla::SetFoldMarginHiColour)
	.def("SetLineIndentation", &PNScintilla::SetLineIndentation)
	.def("SetLineState", &PNScintilla::SetLineState)
	.def("SetHotspotActiveBack", &PNScintilla::SetHotspotActiveBack)
	.def("SetHotspotActiveFore", &PNScintilla::SetHotspotActiveFore)
	.def("SetHotspotActiveUnderline", &PNScintilla::SetHotspotActiveUnderline)
	.def("SetHotspotSingleLine", &PNScintilla::SetHotspotSingleLine)
	.def("SetKeyWords", &PNScintilla::SetKeyWords)
	.def("SetLexerLanguage", &PNScintilla::SetLexerLanguage)
	//.def("SetLengthForEncode", &PNScintilla::SetLengthForEncode)
	.def("SetProperty", &PNScintilla::SetProperty)
	.def("SetSavePoint", &PNScintilla::SetSavePoint)
	.def("SetSel", &PNScintilla::SetSel)
	.def("SetSelBack", &PNScintilla::SetSelBack)
	.def("SetSelFore", &PNScintilla::SetSelFore)
	.def("SetStyling", &PNScintilla::SetStyling)
	.def("SetStylingEx", &PNScintilla::SetStylingEx)
	.def("SetText", &PNScintilla::SetText)
	.def("SetVisiblePolicy", &PNScintilla::SetVisiblePolicy)
	.def("SetWhitespaceBack", &PNScintilla::SetWhitespaceBack)
	.def("SetWhitespaceFore", &PNScintilla::SetWhitespaceFore)
	.def("SetWhitespaceChars", &PNScintilla::SetWhitespaceChars)
	.def("SetWordChars", &PNScintilla::SetWordChars)
	.def("SetXCaretPolicy", &PNScintilla::SetXCaretPolicy)
	.def("SetYCaretPolicy", &PNScintilla::SetYCaretPolicy)
	.def("ShowLines", &PNScintilla::ShowLines)
	.def("StartRecord", &PNScintilla::StartRecord)
	.def("StartStyling", &PNScintilla::StartStyling)
	.def("StopRecord", &PNScintilla::StopRecord)
	.def("StutteredPageDown", &PNScintilla::StutteredPageDown)
	.def("StutteredPageDownExtend", &PNScintilla::StutteredPageDownExtend)
	.def("StutteredPageUp", &PNScintilla::StutteredPageUp)
	.def("StutteredPageUpExtend", &PNScintilla::StutteredPageUpExtend)
	.def("StyleResetDefault", &PNScintilla::StyleResetDefault)
	.def("StyleSetBack", &PNScintilla::StyleSetBack)
	.def("StyleSetBold", &PNScintilla::StyleSetBold)
	.def("StyleSetCase", &PNScintilla::StyleSetCase)
	.def("StyleSetChangeable", &PNScintilla::StyleSetChangeable)
	.def("StyleSetCharacter", &PNScintilla::StyleSetCharacterSet)
	.def("StyleSetClearAll", &PNScintilla::StyleClearAll)
	.def("StyleSetEOLFilled", &PNScintilla::StyleSetEOLFilled)
	.def("StyleSetFont", &PNScintilla::StyleSetFont)
	.def("StyleSetFore", &PNScintilla::StyleSetFore)
	.def("StyleSetHotSpot", &PNScintilla::StyleSetHotSpot)
	.def("StyleSetItalic", &PNScintilla::StyleSetItalic)
	.def("StyleSetSize", &PNScintilla::StyleSetSize)
	.def("StyleSetUnderline", &PNScintilla::StyleSetUnderline)
	.def("StyleSetVisible", &PNScintilla::StyleSetVisible)
	.def("Tab", &PNScintilla::Tab)
	.def("TargetAsUTF8", &PNScintilla::TargetAsUTF8)
	.def("TargetFromSelection", &PNScintilla::TargetFromSelection)
	.def("TextHeight", &PNScintilla::TextHeight)
	.def("TextWidth", &PNScintilla::TextWidth)
	.def("ToggleCaretSticky", &PNScintilla::ToggleCaretSticky)
	.def("ToggleFold", &PNScintilla::ToggleFold)
	.def("Undo", &PNScintilla::Undo)
	.def("UpperCase", &PNScintilla::UpperCase)
	.def("UsePopUp", &PNScintilla::UsePopUp)
	.def("UserListShow", &PNScintilla::UserListShow)
	.def("VCHome", &PNScintilla::VCHome)
	.def("VCHomeExtend", &PNScintilla::VCHomeExtend)
	.def("VCHomeRectExtend", &PNScintilla::VCHomeRectExtend)
	.def("VCHomeWrap", &PNScintilla::VCHomeWrap)
	.def("VCHomeWrapExtend", &PNScintilla::VCHomeWrapExtend)
	.def("VisibleFromDocLine", &PNScintilla::VisibleFromDocLine)
	.def("WordEndPosition", &PNScintilla::WordEndPosition)
	.def("WordLeft", &PNScintilla::WordLeft)
	.def("WordLeftEnd", &PNScintilla::WordLeftEnd)
	.def("WordLeftEndExtend", &PNScintilla::WordLeftEndExtend)
	.def("WordLeftExtend", &PNScintilla::WordLeftExtend)
	.def("WordPartLeft", &PNScintilla::WordPartLeft)
	.def("WordPartLeftExtend", &PNScintilla::WordPartLeftExtend)
	.def("WordPartRight", &PNScintilla::WordPartRight)
	.def("WordPartRightExtend", &PNScintilla::WordPartRightExtend)
	.def("WordRight", &PNScintilla::WordRight)
	.def("WordRightEnd", &PNScintilla::WordRightEnd)
	.def("WordRightEndExtend", &PNScintilla::WordRightEndExtend)
	.def("WordRightExtend", &PNScintilla::WordRightExtend)
	.def("WordStartPosition", &PNScintilla::WordStartPosition)
	//.def("WrapCount", &PNScintilla::WrapCount)
	.def("ZoomIn", &PNScintilla::ZoomIn)
	.def("ZoomOut", &PNScintilla::ZoomOut)

	.def("ClearSelections", &PNScintilla::ClearSelections)
	.def("SetSelection", &PNScintilla::SetSelection)
	.def("AddSelection", &PNScintilla::AddSelection)

	.def("SetSelectionNCaret", &PNScintilla::SetSelectionNCaret)
	.def("GetSelectionNCaret", &PNScintilla::GetSelectionNCaret)
	.def("SetSelectionNCaretVirtualSpace", &PNScintilla::SetSelectionNCaretVirtualSpace)
	.def("GetSelectionNCaretVirtualSpace", &PNScintilla::GetSelectionNCaretVirtualSpace)
	.def("SetSelectionNAnchor", &PNScintilla::SetSelectionNAnchor)
	.def("GetSelectionNAnchor", &PNScintilla::GetSelectionNAnchor)
	.def("SetSelectionNAnchorVirtualSpace", &PNScintilla::SetSelectionNAnchorVirtualSpace)
	.def("GetSelectionNAnchorVirtualSpace", &PNScintilla::GetSelectionNAnchorVirtualSpace)
	.def("SetSelectionNStart", &PNScintilla::SetSelectionNStart)
	.def("GetSelectionNStart", &PNScintilla::GetSelectionNStart)
	.def("SetSelectionNEnd", &PNScintilla::SetSelectionNEnd)
	.def("GetSelectionNEnd", &PNScintilla::GetSelectionNEnd)

	.def("SetAdditionalSelFore", &PNScintilla::SetAdditionalSelFore)
	.def("SetAdditionalSelBack", &PNScintilla::SetAdditionalSelBack)

	.def("SwapMainAnchorCaret", &PNScintilla::SwapMainAnchorCaret)
	.def("RotateSelection", &PNScintilla::RotateSelection)
	;
	scope current;
	current.attr("CARET_EVEN") = 0x08;
	current.attr("CARET_JUMPS") = 0x10;
	current.attr("CARET_SLOP") = 0x01;
	current.attr("CARET_STRICT") = 0x04;
	current.attr("EDGE_BACKGROUND") = 2;
	current.attr("EDGE_LINE") = 1;
	current.attr("EDGE_NONE") = 0;
	current.attr("INDIC0_MASK") = 0x20;
	current.attr("INDIC1_MASK") = 0x40;
	current.attr("INDIC2_MASK") = 0x80;
	current.attr("INDICS_MASK") = 0xE0;
	current.attr("INDIC_BOX") = 6;
	current.attr("INDIC_DIAGONAL") = 3;
	current.attr("INDIC_HIDDEN") = 5;
	current.attr("INDIC_MAX") = 7;
	current.attr("INDIC_PLAIN") = 0;
	current.attr("INDIC_SQUIGGLE") = 1;
	current.attr("INDIC_STRIKE") = 4;
	current.attr("INDIC_TT") = 2;
	current.attr("INVALID_POSITION") = -1;
	current.attr("KEYWORDSET_MAX") = 8;
	current.attr("MARKER_MAX") = 31;
	current.attr("SCEN_CHANGE") = 768;
	current.attr("SCEN_KILLFOCUS") = 256;
	current.attr("SCEN_SETFOCUS") = 512;
	current.attr("SCE_ADA_CHARACTER") = 5;
	current.attr("SCE_ADA_CHARACTEREOL") = 6;
	current.attr("SCE_ADA_COMMENTLINE") = 10;
	current.attr("SCE_ADA_DEFAULT") = 0;
	current.attr("SCE_ADA_DELIMITER") = 4;
	current.attr("SCE_ADA_IDENTIFIER") = 2;
	current.attr("SCE_ADA_ILLEGAL") = 11;
	current.attr("SCE_ADA_LABEL") = 9;
	current.attr("SCE_ADA_NUMBER") = 3;
	current.attr("SCE_ADA_STRING") = 7;
	current.attr("SCE_ADA_STRINGEOL") = 8;
	current.attr("SCE_ADA_WORD") = 1;
	current.attr("SCE_APDL_ARGUMENT") = 11;
	current.attr("SCE_APDL_COMMAND") = 8;
	current.attr("SCE_APDL_COMMENT") = 1;
	current.attr("SCE_APDL_COMMENTBLOCK") = 2;
	current.attr("SCE_APDL_DEFAULT") = 0;
	current.attr("SCE_APDL_FUNCTION") = 12;
	current.attr("SCE_APDL_NUMBER") = 3;
	current.attr("SCE_APDL_OPERATOR") = 5;
	current.attr("SCE_APDL_PROCESSOR") = 7;
	current.attr("SCE_APDL_SLASHCOMMAND") = 9;
	current.attr("SCE_APDL_STARCOMMAND") = 10;
	current.attr("SCE_APDL_STRING") = 4;
	current.attr("SCE_APDL_WORD") = 6;
	current.attr("SCE_ASM_CHARACTER") = 12;
	current.attr("SCE_ASM_COMMENT") = 1;
	current.attr("SCE_ASM_COMMENTBLOCK") = 11;
	current.attr("SCE_ASM_CPUINSTRUCTION") = 6;
	current.attr("SCE_ASM_DEFAULT") = 0;
	current.attr("SCE_ASM_DIRECTIVE") = 9;
	current.attr("SCE_ASM_DIRECTIVEOPERAND") = 10;
	current.attr("SCE_ASM_EXTINSTRUCTION") = 14;
	current.attr("SCE_ASM_IDENTIFIER") = 5;
	current.attr("SCE_ASM_MATHINSTRUCTION") = 7;
	current.attr("SCE_ASM_NUMBER") = 2;
	current.attr("SCE_ASM_OPERATOR") = 4;
	current.attr("SCE_ASM_REGISTER") = 8;
	current.attr("SCE_ASM_STRING") = 3;
	current.attr("SCE_ASM_STRINGEOL") = 13;
	current.attr("SCE_ASN1_ATTRIBUTE") = 7;
	current.attr("SCE_ASN1_COMMENT") = 1;
	current.attr("SCE_ASN1_DEFAULT") = 0;
	current.attr("SCE_ASN1_DESCRIPTOR") = 8;
	current.attr("SCE_ASN1_IDENTIFIER") = 2;
	current.attr("SCE_ASN1_KEYWORD") = 6;
	current.attr("SCE_ASN1_OID") = 4;
	current.attr("SCE_ASN1_OPERATOR") = 10;
	current.attr("SCE_ASN1_SCALAR") = 5;
	current.attr("SCE_ASN1_STRING") = 3;
	current.attr("SCE_ASN1_TYPE") = 9;
	current.attr("SCE_AU3_COMMENT") = 1;
	current.attr("SCE_AU3_COMMENTBLOCK") = 2;
	current.attr("SCE_AU3_COMOBJ") = 14;
	current.attr("SCE_AU3_DEFAULT") = 0;
	current.attr("SCE_AU3_EXPAND") = 13;
	current.attr("SCE_AU3_FUNCTION") = 4;
	current.attr("SCE_AU3_KEYWORD") = 5;
	current.attr("SCE_AU3_MACRO") = 6;
	current.attr("SCE_AU3_NUMBER") = 3;
	current.attr("SCE_AU3_OPERATOR") = 8;
	current.attr("SCE_AU3_PREPROCESSOR") = 11;
	current.attr("SCE_AU3_SENT") = 10;
	current.attr("SCE_AU3_SPECIAL") = 12;
	current.attr("SCE_AU3_STRING") = 7;
	current.attr("SCE_AU3_VARIABLE") = 9;
	current.attr("SCE_AVE_COMMENT") = 1;
	current.attr("SCE_AVE_DEFAULT") = 0;
	current.attr("SCE_AVE_ENUM") = 7;
	current.attr("SCE_AVE_IDENTIFIER") = 9;
	current.attr("SCE_AVE_NUMBER") = 2;
	current.attr("SCE_AVE_OPERATOR") = 10;
	current.attr("SCE_AVE_STRING") = 6;
	current.attr("SCE_AVE_STRINGEOL") = 8;
	current.attr("SCE_AVE_WORD") = 3;
	current.attr("SCE_AVE_WORD1") = 11;
	current.attr("SCE_AVE_WORD2") = 12;
	current.attr("SCE_AVE_WORD3") = 13;
	current.attr("SCE_AVE_WORD4") = 14;
	current.attr("SCE_AVE_WORD5") = 15;
	current.attr("SCE_AVE_WORD6") = 16;
	current.attr("SCE_BAAN_COMMENT") = 1;
	current.attr("SCE_BAAN_COMMENTDOC") = 2;
	current.attr("SCE_BAAN_DEFAULT") = 0;
	current.attr("SCE_BAAN_IDENTIFIER") = 8;
	current.attr("SCE_BAAN_NUMBER") = 3;
	current.attr("SCE_BAAN_OPERATOR") = 7;
	current.attr("SCE_BAAN_PREPROCESSOR") = 6;
	current.attr("SCE_BAAN_STRING") = 5;
	current.attr("SCE_BAAN_STRINGEOL") = 9;
	current.attr("SCE_BAAN_WORD") = 4;
	current.attr("SCE_BAAN_WORD2") = 10;
	current.attr("SCE_BAT_COMMAND") = 5;
	current.attr("SCE_BAT_COMMENT") = 1;
	current.attr("SCE_BAT_DEFAULT") = 0;
	current.attr("SCE_BAT_HIDE") = 4;
	current.attr("SCE_BAT_IDENTIFIER") = 6;
	current.attr("SCE_BAT_LABEL") = 3;
	current.attr("SCE_BAT_OPERATOR") = 7;
	current.attr("SCE_BAT_WORD") = 2;
	current.attr("SCE_B_ASM") = 14;
	current.attr("SCE_B_BINNUMBER") = 18;
	current.attr("SCE_B_COMMENT") = 1;
	current.attr("SCE_B_CONSTANT") = 13;
	current.attr("SCE_B_DATE") = 8;
	current.attr("SCE_B_DEFAULT") = 0;
	current.attr("SCE_B_ERROR") = 16;
	current.attr("SCE_B_HEXNUMBER") = 17;
	current.attr("SCE_B_IDENTIFIER") = 7;
	current.attr("SCE_B_KEYWORD") = 3;
	current.attr("SCE_B_KEYWORD2") = 10;
	current.attr("SCE_B_KEYWORD3") = 11;
	current.attr("SCE_B_KEYWORD4") = 12;
	current.attr("SCE_B_LABEL") = 15;
	current.attr("SCE_B_NUMBER") = 2;
	current.attr("SCE_B_OPERATOR") = 6;
	current.attr("SCE_B_PREPROCESSOR") = 5;
	current.attr("SCE_B_STRING") = 4;
	current.attr("SCE_B_STRINGEOL") = 9;
	current.attr("SCE_CAML_CHAR") = 8;
	current.attr("SCE_CAML_COMMENT") = 10;
	current.attr("SCE_CAML_COMMENT1") = 11;
	current.attr("SCE_CAML_COMMENT2") = 12;
	current.attr("SCE_CAML_COMMENT3") = 13;
	current.attr("SCE_CAML_DEFAULT") = 0;
	current.attr("SCE_CAML_IDENTIFIER") = 1;
	current.attr("SCE_CAML_KEYWORD") = 3;
	current.attr("SCE_CAML_KEYWORD2") = 4;
	current.attr("SCE_CAML_LINENUM") = 5;
	current.attr("SCE_CAML_NUMBER") = 7;
	current.attr("SCE_CAML_OPERATOR") = 6;
	current.attr("SCE_CAML_STRING") = 9;
	current.attr("SCE_CAML_TAGNAME") = 2;
	current.attr("SCE_CLW_ATTRIBUTE") = 13;
	current.attr("SCE_CLW_BUILTIN_PROCEDURES_FUNCTION") = 11;
	current.attr("SCE_CLW_COMMENT") = 2;
	current.attr("SCE_CLW_COMPILER_DIRECTIVE") = 9;
	current.attr("SCE_CLW_DEFAULT") = 0;
	current.attr("SCE_CLW_DEPRECATED") = 16;
	current.attr("SCE_CLW_ERROR") = 15;
	current.attr("SCE_CLW_INTEGER_CONSTANT") = 5;
	current.attr("SCE_CLW_KEYWORD") = 8;
	current.attr("SCE_CLW_LABEL") = 1;
	current.attr("SCE_CLW_PICTURE_STRING") = 7;
	current.attr("SCE_CLW_REAL_CONSTANT") = 6;
	current.attr("SCE_CLW_RUNTIME_EXPRESSIONS") = 10;
	current.attr("SCE_CLW_STANDARD_EQUATE") = 14;
	current.attr("SCE_CLW_STRING") = 3;
	current.attr("SCE_CLW_STRUCTURE_DATA_TYPE") = 12;
	current.attr("SCE_CLW_USER_IDENTIFIER") = 4;
	current.attr("SCE_CONF_COMMENT") = 1;
	current.attr("SCE_CONF_DEFAULT") = 0;
	current.attr("SCE_CONF_DIRECTIVE") = 9;
	current.attr("SCE_CONF_EXTENSION") = 4;
	current.attr("SCE_CONF_IDENTIFIER") = 3;
	current.attr("SCE_CONF_IP") = 8;
	current.attr("SCE_CONF_NUMBER") = 2;
	current.attr("SCE_CONF_OPERATOR") = 7;
	current.attr("SCE_CONF_PARAMETER") = 5;
	current.attr("SCE_CONF_STRING") = 6;
	current.attr("SCE_CSOUND_ARATE_VAR") = 11;
	current.attr("SCE_CSOUND_COMMENT") = 1;
	current.attr("SCE_CSOUND_COMMENTBLOCK") = 9;
	current.attr("SCE_CSOUND_DEFAULT") = 0;
	current.attr("SCE_CSOUND_GLOBAL_VAR") = 14;
	current.attr("SCE_CSOUND_HEADERSTMT") = 7;
	current.attr("SCE_CSOUND_IDENTIFIER") = 5;
	current.attr("SCE_CSOUND_INSTR") = 4;
	current.attr("SCE_CSOUND_IRATE_VAR") = 13;
	current.attr("SCE_CSOUND_KRATE_VAR") = 12;
	current.attr("SCE_CSOUND_NUMBER") = 2;
	current.attr("SCE_CSOUND_OPCODE") = 6;
	current.attr("SCE_CSOUND_OPERATOR") = 3;
	current.attr("SCE_CSOUND_PARAM") = 10;
	current.attr("SCE_CSOUND_STRINGEOL") = 15;
	current.attr("SCE_CSOUND_USERKEYWORD") = 8;
	current.attr("SCE_CSS_ATTRIBUTE") = 16;
	current.attr("SCE_CSS_CLASS") = 2;
	current.attr("SCE_CSS_COMMENT") = 9;
	current.attr("SCE_CSS_DEFAULT") = 0;
	current.attr("SCE_CSS_DIRECTIVE") = 12;
	current.attr("SCE_CSS_DOUBLESTRING") = 13;
	current.attr("SCE_CSS_ID") = 10;
	current.attr("SCE_CSS_IDENTIFIER") = 6;
	current.attr("SCE_CSS_IDENTIFIER2") = 15;
	current.attr("SCE_CSS_IMPORTANT") = 11;
	current.attr("SCE_CSS_OPERATOR") = 5;
	current.attr("SCE_CSS_PSEUDOCLASS") = 3;
	current.attr("SCE_CSS_SINGLESTRING") = 14;
	current.attr("SCE_CSS_TAG") = 1;
	current.attr("SCE_CSS_UNKNOWN_IDENTIFIER") = 7;
	current.attr("SCE_CSS_UNKNOWN_PSEUDOCLASS") = 4;
	current.attr("SCE_CSS_VALUE") = 8;
	current.attr("SCE_C_CHARACTER") = 7;
	current.attr("SCE_C_COMMENT") = 1;
	current.attr("SCE_C_COMMENTDOC") = 3;
	current.attr("SCE_C_COMMENTDOCKEYWORD") = 17;
	current.attr("SCE_C_COMMENTDOCKEYWORDERROR") = 18;
	current.attr("SCE_C_COMMENTLINE") = 2;
	current.attr("SCE_C_COMMENTLINEDOC") = 15;
	current.attr("SCE_C_DEFAULT") = 0;
	current.attr("SCE_C_GLOBALCLASS") = 19;
	current.attr("SCE_C_IDENTIFIER") = 11;
	current.attr("SCE_C_NUMBER") = 4;
	current.attr("SCE_C_OPERATOR") = 10;
	current.attr("SCE_C_PREPROCESSOR") = 9;
	current.attr("SCE_C_REGEX") = 14;
	current.attr("SCE_C_STRING") = 6;
	current.attr("SCE_C_STRINGEOL") = 12;
	current.attr("SCE_C_UUID") = 8;
	current.attr("SCE_C_VERBATIM") = 13;
	current.attr("SCE_C_WORD") = 5;
	current.attr("SCE_C_WORD2") = 16;
	current.attr("SCE_DIFF_ADDED") = 6;
	current.attr("SCE_DIFF_COMMAND") = 2;
	current.attr("SCE_DIFF_COMMENT") = 1;
	current.attr("SCE_DIFF_DEFAULT") = 0;
	current.attr("SCE_DIFF_DELETED") = 5;
	current.attr("SCE_DIFF_HEADER") = 3;
	current.attr("SCE_DIFF_POSITION") = 4;
	current.attr("SCE_EIFFEL_CHARACTER") = 5;
	current.attr("SCE_EIFFEL_COMMENTLINE") = 1;
	current.attr("SCE_EIFFEL_DEFAULT") = 0;
	current.attr("SCE_EIFFEL_IDENTIFIER") = 7;
	current.attr("SCE_EIFFEL_NUMBER") = 2;
	current.attr("SCE_EIFFEL_OPERATOR") = 6;
	current.attr("SCE_EIFFEL_STRING") = 4;
	current.attr("SCE_EIFFEL_STRINGEOL") = 8;
	current.attr("SCE_EIFFEL_WORD") = 3;
	current.attr("SCE_ERLANG_ATOM") = 7;
	current.attr("SCE_ERLANG_CHARACTER") = 9;
	current.attr("SCE_ERLANG_COMMENT") = 1;
	current.attr("SCE_ERLANG_DEFAULT") = 0;
	current.attr("SCE_ERLANG_FUNCTION_NAME") = 8;
	current.attr("SCE_ERLANG_KEYWORD") = 4;
	current.attr("SCE_ERLANG_MACRO") = 10;
	current.attr("SCE_ERLANG_NODE_NAME") = 13;
	current.attr("SCE_ERLANG_NUMBER") = 3;
	current.attr("SCE_ERLANG_OPERATOR") = 6;
	current.attr("SCE_ERLANG_RECORD") = 11;
	current.attr("SCE_ERLANG_SEPARATOR") = 12;
	current.attr("SCE_ERLANG_STRING") = 5;
	current.attr("SCE_ERLANG_UNKNOWN") = 31;
	current.attr("SCE_ERLANG_VARIABLE") = 2;
	current.attr("SCE_ERR_ABSF") = 18;
	current.attr("SCE_ERR_BORLAND") = 5;
	current.attr("SCE_ERR_CMD") = 4;
	current.attr("SCE_ERR_CTAG") = 9;
	current.attr("SCE_ERR_DEFAULT") = 0;
	current.attr("SCE_ERR_DIFF_ADDITION") = 11;
	current.attr("SCE_ERR_DIFF_CHANGED") = 10;
	current.attr("SCE_ERR_DIFF_DELETION") = 12;
	current.attr("SCE_ERR_DIFF_MESSAGE") = 13;
	current.attr("SCE_ERR_ELF") = 15;
	current.attr("SCE_ERR_GCC") = 2;
	current.attr("SCE_ERR_IFC") = 16;
	current.attr("SCE_ERR_IFORT") = 17;
	current.attr("SCE_ERR_JAVA_STACK") = 20;
	current.attr("SCE_ERR_LUA") = 8;
	current.attr("SCE_ERR_MS") = 3;
	current.attr("SCE_ERR_NET") = 7;
	current.attr("SCE_ERR_PERL") = 6;
	current.attr("SCE_ERR_PHP") = 14;
	current.attr("SCE_ERR_PYTHON") = 1;
	current.attr("SCE_ERR_TIDY") = 19;
	current.attr("SCE_ESCRIPT_BRACE") = 9;
	current.attr("SCE_ESCRIPT_COMMENT") = 1;
	current.attr("SCE_ESCRIPT_COMMENTDOC") = 3;
	current.attr("SCE_ESCRIPT_COMMENTLINE") = 2;
	current.attr("SCE_ESCRIPT_DEFAULT") = 0;
	current.attr("SCE_ESCRIPT_IDENTIFIER") = 8;
	current.attr("SCE_ESCRIPT_NUMBER") = 4;
	current.attr("SCE_ESCRIPT_OPERATOR") = 7;
	current.attr("SCE_ESCRIPT_STRING") = 6;
	current.attr("SCE_ESCRIPT_WORD") = 5;
	current.attr("SCE_ESCRIPT_WORD2") = 10;
	current.attr("SCE_ESCRIPT_WORD3") = 11;
	current.attr("SCE_FORTH_COMMENT") = 1;
	current.attr("SCE_FORTH_COMMENT_ML") = 2;
	current.attr("SCE_FORTH_CONTROL") = 4;
	current.attr("SCE_FORTH_DEFAULT") = 0;
	current.attr("SCE_FORTH_DEFWORD") = 6;
	current.attr("SCE_FORTH_IDENTIFIER") = 3;
	current.attr("SCE_FORTH_KEYWORD") = 5;
	current.attr("SCE_FORTH_LOCALE") = 11;
	current.attr("SCE_FORTH_NUMBER") = 9;
	current.attr("SCE_FORTH_PREWORD1") = 7;
	current.attr("SCE_FORTH_PREWORD2") = 8;
	current.attr("SCE_FORTH_STRING") = 10;
	current.attr("SCE_FS_ASM") = 19;
	current.attr("SCE_FS_BINNUMBER") = 23;
	current.attr("SCE_FS_COMMENT") = 1;
	current.attr("SCE_FS_COMMENTDOC") = 3;
	current.attr("SCE_FS_COMMENTDOCKEYWORD") = 5;
	current.attr("SCE_FS_COMMENTDOCKEYWORDERROR") = 6;
	current.attr("SCE_FS_COMMENTLINE") = 2;
	current.attr("SCE_FS_COMMENTLINEDOC") = 4;
	current.attr("SCE_FS_CONSTANT") = 18;
	current.attr("SCE_FS_DATE") = 16;
	current.attr("SCE_FS_DEFAULT") = 0;
	current.attr("SCE_FS_ERROR") = 21;
	current.attr("SCE_FS_HEXNUMBER") = 22;
	current.attr("SCE_FS_IDENTIFIER") = 15;
	current.attr("SCE_FS_KEYWORD") = 7;
	current.attr("SCE_FS_KEYWORD2") = 8;
	current.attr("SCE_FS_KEYWORD3") = 9;
	current.attr("SCE_FS_KEYWORD4") = 10;
	current.attr("SCE_FS_LABEL") = 20;
	current.attr("SCE_FS_NUMBER") = 11;
	current.attr("SCE_FS_OPERATOR") = 14;
	current.attr("SCE_FS_PREPROCESSOR") = 13;
	current.attr("SCE_FS_STRING") = 12;
	current.attr("SCE_FS_STRINGEOL") = 17;
	current.attr("SCE_F_COMMENT") = 1;
	current.attr("SCE_F_CONTINUATION") = 14;
	current.attr("SCE_F_DEFAULT") = 0;
	current.attr("SCE_F_IDENTIFIER") = 7;
	current.attr("SCE_F_LABEL") = 13;
	current.attr("SCE_F_NUMBER") = 2;
	current.attr("SCE_F_OPERATOR") = 6;
	current.attr("SCE_F_OPERATOR2") = 12;
	current.attr("SCE_F_PREPROCESSOR") = 11;
	current.attr("SCE_F_STRING1") = 3;
	current.attr("SCE_F_STRING2") = 4;
	current.attr("SCE_F_STRINGEOL") = 5;
	current.attr("SCE_F_WORD") = 8;
	current.attr("SCE_F_WORD2") = 9;
	current.attr("SCE_F_WORD3") = 10;
	current.attr("SCE_GC_ATTRIBUTE") = 5;
	current.attr("SCE_GC_COMMAND") = 7;
	current.attr("SCE_GC_COMMENTBLOCK") = 2;
	current.attr("SCE_GC_COMMENTLINE") = 1;
	current.attr("SCE_GC_CONTROL") = 6;
	current.attr("SCE_GC_DEFAULT") = 0;
	current.attr("SCE_GC_EVENT") = 4;
	current.attr("SCE_GC_GLOBAL") = 3;
	current.attr("SCE_GC_OPERATOR") = 9;
	current.attr("SCE_GC_STRING") = 8;
	current.attr("SCE_HA_CAPITAL") = 8;
	current.attr("SCE_HA_CHARACTER") = 5;
	current.attr("SCE_HA_CLASS") = 6;
	current.attr("SCE_HA_COMMENTBLOCK") = 14;
	current.attr("SCE_HA_COMMENTBLOCK2") = 15;
	current.attr("SCE_HA_COMMENTBLOCK3") = 16;
	current.attr("SCE_HA_COMMENTLINE") = 13;
	current.attr("SCE_HA_DATA") = 9;
	current.attr("SCE_HA_DEFAULT") = 0;
	current.attr("SCE_HA_IDENTIFIER") = 1;
	current.attr("SCE_HA_IMPORT") = 10;
	current.attr("SCE_HA_INSTANCE") = 12;
	current.attr("SCE_HA_KEYWORD") = 2;
	current.attr("SCE_HA_MODULE") = 7;
	current.attr("SCE_HA_NUMBER") = 3;
	current.attr("SCE_HA_OPERATOR") = 11;
	current.attr("SCE_HA_STRING") = 4;
	current.attr("SCE_HBA_COMMENTLINE") = 82;
	current.attr("SCE_HBA_DEFAULT") = 81;
	current.attr("SCE_HBA_IDENTIFIER") = 86;
	current.attr("SCE_HBA_NUMBER") = 83;
	current.attr("SCE_HBA_START") = 80;
	current.attr("SCE_HBA_STRING") = 85;
	current.attr("SCE_HBA_STRINGEOL") = 87;
	current.attr("SCE_HBA_WORD") = 84;
	current.attr("SCE_HB_COMMENTLINE") = 72;
	current.attr("SCE_HB_DEFAULT") = 71;
	current.attr("SCE_HB_IDENTIFIER") = 76;
	current.attr("SCE_HB_NUMBER") = 73;
	current.attr("SCE_HB_START") = 70;
	current.attr("SCE_HB_STRING") = 75;
	current.attr("SCE_HB_STRINGEOL") = 77;
	current.attr("SCE_HB_WORD") = 74;
	current.attr("SCE_HJA_COMMENT") = 57;
	current.attr("SCE_HJA_COMMENTDOC") = 59;
	current.attr("SCE_HJA_COMMENTLINE") = 58;
	current.attr("SCE_HJA_DEFAULT") = 56;
	current.attr("SCE_HJA_DOUBLESTRING") = 63;
	current.attr("SCE_HJA_KEYWORD") = 62;
	current.attr("SCE_HJA_NUMBER") = 60;
	current.attr("SCE_HJA_REGEX") = 67;
	current.attr("SCE_HJA_SINGLESTRING") = 64;
	current.attr("SCE_HJA_START") = 55;
	current.attr("SCE_HJA_STRINGEOL") = 66;
	current.attr("SCE_HJA_SYMBOLS") = 65;
	current.attr("SCE_HJA_WORD") = 61;
	current.attr("SCE_HJ_COMMENT") = 42;
	current.attr("SCE_HJ_COMMENTDOC") = 44;
	current.attr("SCE_HJ_COMMENTLINE") = 43;
	current.attr("SCE_HJ_DEFAULT") = 41;
	current.attr("SCE_HJ_DOUBLESTRING") = 48;
	current.attr("SCE_HJ_KEYWORD") = 47;
	current.attr("SCE_HJ_NUMBER") = 45;
	current.attr("SCE_HJ_REGEX") = 52;
	current.attr("SCE_HJ_SINGLESTRING") = 49;
	current.attr("SCE_HJ_START") = 40;
	current.attr("SCE_HJ_STRINGEOL") = 51;
	current.attr("SCE_HJ_SYMBOLS") = 50;
	current.attr("SCE_HJ_WORD") = 46;
	current.attr("SCE_HPA_CHARACTER") = 110;
	current.attr("SCE_HPA_CLASSNAME") = 114;
	current.attr("SCE_HPA_COMMENTLINE") = 107;
	current.attr("SCE_HPA_DEFAULT") = 106;
	current.attr("SCE_HPA_DEFNAME") = 115;
	current.attr("SCE_HPA_IDENTIFIER") = 117;
	current.attr("SCE_HPA_NUMBER") = 108;
	current.attr("SCE_HPA_OPERATOR") = 116;
	current.attr("SCE_HPA_START") = 105;
	current.attr("SCE_HPA_STRING") = 109;
	current.attr("SCE_HPA_TRIPLE") = 112;
	current.attr("SCE_HPA_TRIPLEDOUBLE") = 113;
	current.attr("SCE_HPA_WORD") = 111;
	current.attr("SCE_HPHP_COMMENT") = 124;
	current.attr("SCE_HPHP_COMMENTLINE") = 125;
	current.attr("SCE_HPHP_COMPLEX_VARIABLE") = 104;
	current.attr("SCE_HPHP_DEFAULT") = 118;
	current.attr("SCE_HPHP_HSTRING") = 119;
	current.attr("SCE_HPHP_HSTRING_VARIABLE") = 126;
	current.attr("SCE_HPHP_NUMBER") = 122;
	current.attr("SCE_HPHP_OPERATOR") = 127;
	current.attr("SCE_HPHP_SIMPLESTRING") = 120;
	current.attr("SCE_HPHP_VARIABLE") = 123;
	current.attr("SCE_HPHP_WORD") = 121;
	current.attr("SCE_HP_CHARACTER") = 95;
	current.attr("SCE_HP_CLASSNAME") = 99;
	current.attr("SCE_HP_COMMENTLINE") = 92;
	current.attr("SCE_HP_DEFAULT") = 91;
	current.attr("SCE_HP_DEFNAME") = 100;
	current.attr("SCE_HP_IDENTIFIER") = 102;
	current.attr("SCE_HP_NUMBER") = 93;
	current.attr("SCE_HP_OPERATOR") = 101;
	current.attr("SCE_HP_START") = 90;
	current.attr("SCE_HP_STRING") = 94;
	current.attr("SCE_HP_TRIPLE") = 97;
	current.attr("SCE_HP_TRIPLEDOUBLE") = 98;
	current.attr("SCE_HP_WORD") = 96;
	current.attr("SCE_H_ASP") = 15;
	current.attr("SCE_H_ASPAT") = 16;
	current.attr("SCE_H_ATTRIBUTE") = 3;
	current.attr("SCE_H_ATTRIBUTEUNKNOWN") = 4;
	current.attr("SCE_H_CDATA") = 17;
	current.attr("SCE_H_COMMENT") = 9;
	current.attr("SCE_H_DEFAULT") = 0;
	current.attr("SCE_H_DOUBLESTRING") = 6;
	current.attr("SCE_H_ENTITY") = 10;
	current.attr("SCE_H_NUMBER") = 5;
	current.attr("SCE_H_OTHER") = 8;
	current.attr("SCE_H_QUESTION") = 18;
	current.attr("SCE_H_SCRIPT") = 14;
	current.attr("SCE_H_SGML_1ST_PARAM") = 23;
	current.attr("SCE_H_SGML_1ST_PARAM_COMMENT") = 30;
	current.attr("SCE_H_SGML_BLOCK_DEFAULT") = 31;
	current.attr("SCE_H_SGML_COMMAND") = 22;
	current.attr("SCE_H_SGML_COMMENT") = 29;
	current.attr("SCE_H_SGML_DEFAULT") = 21;
	current.attr("SCE_H_SGML_DOUBLESTRING") = 24;
	current.attr("SCE_H_SGML_ENTITY") = 28;
	current.attr("SCE_H_SGML_ERROR") = 26;
	current.attr("SCE_H_SGML_SIMPLESTRING") = 25;
	current.attr("SCE_H_SGML_SPECIAL") = 27;
	current.attr("SCE_H_SINGLESTRING") = 7;
	current.attr("SCE_H_TAG") = 1;
	current.attr("SCE_H_TAGEND") = 11;
	current.attr("SCE_H_TAGUNKNOWN") = 2;
	current.attr("SCE_H_VALUE") = 19;
	current.attr("SCE_H_XCCOMMENT") = 20;
	current.attr("SCE_H_XMLEND") = 13;
	current.attr("SCE_H_XMLSTART") = 12;
	current.attr("SCE_KIX_COMMENT") = 1;
	current.attr("SCE_KIX_DEFAULT") = 0;
	current.attr("SCE_KIX_FUNCTIONS") = 8;
	current.attr("SCE_KIX_IDENTIFIER") = 31;
	current.attr("SCE_KIX_KEYWORD") = 7;
	current.attr("SCE_KIX_MACRO") = 6;
	current.attr("SCE_KIX_NUMBER") = 4;
	current.attr("SCE_KIX_OPERATOR") = 9;
	current.attr("SCE_KIX_STRING1") = 2;
	current.attr("SCE_KIX_STRING2") = 3;
	current.attr("SCE_KIX_VAR") = 5;
	current.attr("SCE_LISP_COMMENT") = 1;
	current.attr("SCE_LISP_DEFAULT") = 0;
	current.attr("SCE_LISP_IDENTIFIER") = 9;
	current.attr("SCE_LISP_KEYWORD") = 3;
	current.attr("SCE_LISP_KEYWORD_KW") = 4;
	current.attr("SCE_LISP_MULTI_COMMENT") = 12;
	current.attr("SCE_LISP_NUMBER") = 2;
	current.attr("SCE_LISP_OPERATOR") = 10;
	current.attr("SCE_LISP_SPECIAL") = 11;
	current.attr("SCE_LISP_STRING") = 6;
	current.attr("SCE_LISP_STRINGEOL") = 8;
	current.attr("SCE_LISP_SYMBOL") = 5;
	current.attr("SCE_LOT_ABORT") = 6;
	current.attr("SCE_LOT_BREAK") = 2;
	current.attr("SCE_LOT_DEFAULT") = 0;
	current.attr("SCE_LOT_FAIL") = 5;
	current.attr("SCE_LOT_HEADER") = 1;
	current.attr("SCE_LOT_PASS") = 4;
	current.attr("SCE_LOT_SET") = 3;
	current.attr("SCE_LOUT_COMMENT") = 1;
	current.attr("SCE_LOUT_DEFAULT") = 0;
	current.attr("SCE_LOUT_IDENTIFIER") = 9;
	current.attr("SCE_LOUT_NUMBER") = 2;
	current.attr("SCE_LOUT_OPERATOR") = 8;
	current.attr("SCE_LOUT_STRING") = 7;
	current.attr("SCE_LOUT_STRINGEOL") = 10;
	current.attr("SCE_LOUT_WORD") = 3;
	current.attr("SCE_LOUT_WORD2") = 4;
	current.attr("SCE_LOUT_WORD3") = 5;
	current.attr("SCE_LOUT_WORD4") = 6;
	current.attr("SCE_LUA_CHARACTER") = 7;
	current.attr("SCE_LUA_COMMENT") = 1;
	current.attr("SCE_LUA_COMMENTDOC") = 3;
	current.attr("SCE_LUA_COMMENTLINE") = 2;
	current.attr("SCE_LUA_DEFAULT") = 0;
	current.attr("SCE_LUA_IDENTIFIER") = 11;
	current.attr("SCE_LUA_LITERALSTRING") = 8;
	current.attr("SCE_LUA_NUMBER") = 4;
	current.attr("SCE_LUA_OPERATOR") = 10;
	current.attr("SCE_LUA_PREPROCESSOR") = 9;
	current.attr("SCE_LUA_STRING") = 6;
	current.attr("SCE_LUA_STRINGEOL") = 12;
	current.attr("SCE_LUA_WORD") = 5;
	current.attr("SCE_LUA_WORD2") = 13;
	current.attr("SCE_LUA_WORD3") = 14;
	current.attr("SCE_LUA_WORD4") = 15;
	current.attr("SCE_LUA_WORD5") = 16;
	current.attr("SCE_LUA_WORD6") = 17;
	current.attr("SCE_LUA_WORD7") = 18;
	current.attr("SCE_LUA_WORD8") = 19;
	current.attr("SCE_L_COMMAND") = 1;
	current.attr("SCE_L_COMMENT") = 4;
	current.attr("SCE_L_DEFAULT") = 0;
	current.attr("SCE_L_MATH") = 3;
	current.attr("SCE_L_TAG") = 2;
	current.attr("SCE_MAKE_COMMENT") = 1;
	current.attr("SCE_MAKE_DEFAULT") = 0;
	current.attr("SCE_MAKE_IDENTIFIER") = 3;
	current.attr("SCE_MAKE_IDEOL") = 9;
	current.attr("SCE_MAKE_OPERATOR") = 4;
	current.attr("SCE_MAKE_PREPROCESSOR") = 2;
	current.attr("SCE_MAKE_TARGET") = 5;
	current.attr("SCE_MATLAB_COMMAND") = 2;
	current.attr("SCE_MATLAB_COMMENT") = 1;
	current.attr("SCE_MATLAB_DEFAULT") = 0;
	current.attr("SCE_MATLAB_DOUBLEQUOTESTRING") = 8;
	current.attr("SCE_MATLAB_IDENTIFIER") = 7;
	current.attr("SCE_MATLAB_KEYWORD") = 4;
	current.attr("SCE_MATLAB_NUMBER") = 3;
	current.attr("SCE_MATLAB_OPERATOR") = 6;
	current.attr("SCE_MATLAB_STRING") = 5;
	current.attr("SCE_METAPOST_COMMAND") = 4;
	current.attr("SCE_METAPOST_DEFAULT") = 0;
	current.attr("SCE_METAPOST_EXTRA") = 6;
	current.attr("SCE_METAPOST_GROUP") = 2;
	current.attr("SCE_METAPOST_SPECIAL") = 1;
	current.attr("SCE_METAPOST_SYMBOL") = 3;
	current.attr("SCE_METAPOST_TEXT") = 5;
	current.attr("SCE_MMIXAL_CHAR") = 11;
	current.attr("SCE_MMIXAL_COMMENT") = 1;
	current.attr("SCE_MMIXAL_HEX") = 14;
	current.attr("SCE_MMIXAL_INCLUDE") = 17;
	current.attr("SCE_MMIXAL_LABEL") = 2;
	current.attr("SCE_MMIXAL_LEADWS") = 0;
	current.attr("SCE_MMIXAL_NUMBER") = 9;
	current.attr("SCE_MMIXAL_OPCODE") = 3;
	current.attr("SCE_MMIXAL_OPCODE_POST") = 7;
	current.attr("SCE_MMIXAL_OPCODE_PRE") = 4;
	current.attr("SCE_MMIXAL_OPCODE_UNKNOWN") = 6;
	current.attr("SCE_MMIXAL_OPCODE_VALID") = 5;
	current.attr("SCE_MMIXAL_OPERANDS") = 8;
	current.attr("SCE_MMIXAL_OPERATOR") = 15;
	current.attr("SCE_MMIXAL_REF") = 10;
	current.attr("SCE_MMIXAL_REGISTER") = 13;
	current.attr("SCE_MMIXAL_STRING") = 12;
	current.attr("SCE_MMIXAL_SYMBOL") = 16;
	current.attr("SCE_MSSQL_COLUMN_NAME") = 8;
	current.attr("SCE_MSSQL_COLUMN_NAME_2") = 16;
	current.attr("SCE_MSSQL_COMMENT") = 1;
	current.attr("SCE_MSSQL_DATATYPE") = 10;
	current.attr("SCE_MSSQL_DEFAULT") = 0;
	current.attr("SCE_MSSQL_DEFAULT_PREF_DATATYPE") = 15;
	current.attr("SCE_MSSQL_FUNCTION") = 13;
	current.attr("SCE_MSSQL_GLOBAL_VARIABLE") = 12;
	current.attr("SCE_MSSQL_IDENTIFIER") = 6;
	current.attr("SCE_MSSQL_LINE_COMMENT") = 2;
	current.attr("SCE_MSSQL_NUMBER") = 3;
	current.attr("SCE_MSSQL_OPERATOR") = 5;
	current.attr("SCE_MSSQL_STATEMENT") = 9;
	current.attr("SCE_MSSQL_STORED_PROCEDURE") = 14;
	current.attr("SCE_MSSQL_STRING") = 4;
	current.attr("SCE_MSSQL_SYSTABLE") = 11;
	current.attr("SCE_MSSQL_VARIABLE") = 7;
	current.attr("SCE_NNCRONTAB_ASTERISK") = 6;
	current.attr("SCE_NNCRONTAB_COMMENT") = 1;
	current.attr("SCE_NNCRONTAB_DEFAULT") = 0;
	current.attr("SCE_NNCRONTAB_ENVIRONMENT") = 9;
	current.attr("SCE_NNCRONTAB_IDENTIFIER") = 10;
	current.attr("SCE_NNCRONTAB_KEYWORD") = 4;
	current.attr("SCE_NNCRONTAB_MODIFIER") = 5;
	current.attr("SCE_NNCRONTAB_NUMBER") = 7;
	current.attr("SCE_NNCRONTAB_SECTION") = 3;
	current.attr("SCE_NNCRONTAB_STRING") = 8;
	current.attr("SCE_NNCRONTAB_TASK") = 2;
	current.attr("SCE_NSIS_COMMENT") = 1;
	current.attr("SCE_NSIS_COMMENTBOX") = 18;
	current.attr("SCE_NSIS_DEFAULT") = 0;
	current.attr("SCE_NSIS_FUNCTION") = 5;
	current.attr("SCE_NSIS_FUNCTIONDEF") = 17;
	current.attr("SCE_NSIS_IFDEFINEDEF") = 11;
	current.attr("SCE_NSIS_LABEL") = 7;
	current.attr("SCE_NSIS_MACRODEF") = 12;
	current.attr("SCE_NSIS_NUMBER") = 14;
	current.attr("SCE_NSIS_PAGEEX") = 16;
	current.attr("SCE_NSIS_SECTIONDEF") = 9;
	current.attr("SCE_NSIS_SECTIONGROUP") = 15;
	current.attr("SCE_NSIS_STRINGDQ") = 2;
	current.attr("SCE_NSIS_STRINGLQ") = 3;
	current.attr("SCE_NSIS_STRINGRQ") = 4;
	current.attr("SCE_NSIS_STRINGVAR") = 13;
	current.attr("SCE_NSIS_SUBSECTIONDEF") = 10;
	current.attr("SCE_NSIS_USERDEFINED") = 8;
	current.attr("SCE_NSIS_VARIABLE") = 6;
	current.attr("SCE_PL_ARRAY") = 13;
	current.attr("SCE_PL_BACKTICKS") = 20;
	current.attr("SCE_PL_CHARACTER") = 7;
	current.attr("SCE_PL_COMMENTLINE") = 2;
	current.attr("SCE_PL_DATASECTION") = 21;
	current.attr("SCE_PL_DEFAULT") = 0;
	current.attr("SCE_PL_ERROR") = 1;
	current.attr("SCE_PL_HASH") = 14;
	current.attr("SCE_PL_HERE_DELIM") = 22;
	current.attr("SCE_PL_HERE_Q") = 23;
	current.attr("SCE_PL_HERE_QQ") = 24;
	current.attr("SCE_PL_HERE_QX") = 25;
	current.attr("SCE_PL_IDENTIFIER") = 11;
	current.attr("SCE_PL_LONGQUOTE") = 19;
	current.attr("SCE_PL_NUMBER") = 4;
	current.attr("SCE_PL_OPERATOR") = 10;
	current.attr("SCE_PL_POD") = 3;
	current.attr("SCE_PL_POD_VERB") = 31;
	current.attr("SCE_PL_PREPROCESSOR") = 9;
	current.attr("SCE_PL_PUNCTUATION") = 8;
	current.attr("SCE_PL_REGEX") = 17;
	current.attr("SCE_PL_REGSUBST") = 18;
	current.attr("SCE_PL_SCALAR") = 12;
	current.attr("SCE_PL_STRING") = 6;
	current.attr("SCE_PL_STRING_Q") = 26;
	current.attr("SCE_PL_STRING_QQ") = 27;
	current.attr("SCE_PL_STRING_QR") = 29;
	current.attr("SCE_PL_STRING_QW") = 30;
	current.attr("SCE_PL_STRING_QX") = 28;
	current.attr("SCE_PL_SYMBOLTABLE") = 15;
	current.attr("SCE_PL_VARIABLE_INDEXER") = 16;
	current.attr("SCE_PL_WORD") = 5;
	current.attr("SCE_POV_BADDIRECTIVE") = 9;
	current.attr("SCE_POV_COMMENT") = 1;
	current.attr("SCE_POV_COMMENTLINE") = 2;
	current.attr("SCE_POV_DEFAULT") = 0;
	current.attr("SCE_POV_DIRECTIVE") = 8;
	current.attr("SCE_POV_IDENTIFIER") = 5;
	current.attr("SCE_POV_NUMBER") = 3;
	current.attr("SCE_POV_OPERATOR") = 4;
	current.attr("SCE_POV_STRING") = 6;
	current.attr("SCE_POV_STRINGEOL") = 7;
	current.attr("SCE_POV_WORD2") = 10;
	current.attr("SCE_POV_WORD3") = 11;
	current.attr("SCE_POV_WORD4") = 12;
	current.attr("SCE_POV_WORD5") = 13;
	current.attr("SCE_POV_WORD6") = 14;
	current.attr("SCE_POV_WORD7") = 15;
	current.attr("SCE_POV_WORD8") = 16;
	current.attr("SCE_PROPS_ASSIGNMENT") = 3;
	current.attr("SCE_PROPS_COMMENT") = 1;
	current.attr("SCE_PROPS_DEFAULT") = 0;
	current.attr("SCE_PROPS_DEFVAL") = 4;
	current.attr("SCE_PROPS_SECTION") = 2;
	current.attr("SCE_PS_BADSTRINGCHAR") = 15;
	current.attr("SCE_PS_BASE85STRING") = 14;
	current.attr("SCE_PS_COMMENT") = 1;
	current.attr("SCE_PS_DEFAULT") = 0;
	current.attr("SCE_PS_DSC_COMMENT") = 2;
	current.attr("SCE_PS_DSC_VALUE") = 3;
	current.attr("SCE_PS_HEXSTRING") = 13;
	current.attr("SCE_PS_IMMEVAL") = 8;
	current.attr("SCE_PS_KEYWORD") = 6;
	current.attr("SCE_PS_LITERAL") = 7;
	current.attr("SCE_PS_NAME") = 5;
	current.attr("SCE_PS_NUMBER") = 4;
	current.attr("SCE_PS_PAREN_ARRAY") = 9;
	current.attr("SCE_PS_PAREN_DICT") = 10;
	current.attr("SCE_PS_PAREN_PROC") = 11;
	current.attr("SCE_PS_TEXT") = 12;
	current.attr("SCE_P_CHARACTER") = 4;
	current.attr("SCE_P_CLASSNAME") = 8;
	current.attr("SCE_P_COMMENTBLOCK") = 12;
	current.attr("SCE_P_COMMENTLINE") = 1;
	current.attr("SCE_P_DEFAULT") = 0;
	current.attr("SCE_P_DEFNAME") = 9;
	current.attr("SCE_P_IDENTIFIER") = 11;
	current.attr("SCE_P_NUMBER") = 2;
	current.attr("SCE_P_OPERATOR") = 10;
	current.attr("SCE_P_STRING") = 3;
	current.attr("SCE_P_STRINGEOL") = 13;
	current.attr("SCE_P_TRIPLE") = 6;
	current.attr("SCE_P_TRIPLEDOUBLE") = 7;
	current.attr("SCE_P_WORD") = 5;
	current.attr("SCE_RB_BACKTICKS") = 18;
	current.attr("SCE_RB_CHARACTER") = 7;
	current.attr("SCE_RB_CLASSNAME") = 8;
	current.attr("SCE_RB_CLASS_VAR") = 17;
	current.attr("SCE_RB_COMMENTLINE") = 2;
	current.attr("SCE_RB_DATASECTION") = 19;
	current.attr("SCE_RB_DEFAULT") = 0;
	current.attr("SCE_RB_DEFNAME") = 9;
	current.attr("SCE_RB_ERROR") = 1;
	current.attr("SCE_RB_GLOBAL") = 13;
	current.attr("SCE_RB_HERE_DELIM") = 20;
	current.attr("SCE_RB_HERE_Q") = 21;
	current.attr("SCE_RB_HERE_QQ") = 22;
	current.attr("SCE_RB_HERE_QX") = 23;
	current.attr("SCE_RB_IDENTIFIER") = 11;
	current.attr("SCE_RB_INSTANCE_VAR") = 16;
	current.attr("SCE_RB_MODULE_NAME") = 15;
	current.attr("SCE_RB_NUMBER") = 4;
	current.attr("SCE_RB_OPERATOR") = 10;
	current.attr("SCE_RB_POD") = 3;
	current.attr("SCE_RB_REGEX") = 12;
	current.attr("SCE_RB_STDERR") = 40;
	current.attr("SCE_RB_STDIN") = 30;
	current.attr("SCE_RB_STDOUT") = 31;
	current.attr("SCE_RB_STRING") = 6;
	current.attr("SCE_RB_STRING_Q") = 24;
	current.attr("SCE_RB_STRING_QQ") = 25;
	current.attr("SCE_RB_STRING_QR") = 27;
	current.attr("SCE_RB_STRING_QW") = 28;
	current.attr("SCE_RB_STRING_QX") = 26;
	current.attr("SCE_RB_SYMBOL") = 14;
	current.attr("SCE_RB_UPPER_BOUND") = 41;
	current.attr("SCE_RB_WORD") = 5;
	current.attr("SCE_RB_WORD_DEMOTED") = 29;
	current.attr("SCE_REBOL_BINARY") = 11;
	current.attr("SCE_REBOL_BRACEDSTRING") = 7;
	current.attr("SCE_REBOL_CHARACTER") = 5;
	current.attr("SCE_REBOL_COMMENTBLOCK") = 2;
	current.attr("SCE_REBOL_COMMENTLINE") = 1;
	current.attr("SCE_REBOL_DATE") = 18;
	current.attr("SCE_REBOL_DEFAULT") = 0;
	current.attr("SCE_REBOL_EMAIL") = 16;
	current.attr("SCE_REBOL_FILE") = 15;
	current.attr("SCE_REBOL_IDENTIFIER") = 20;
	current.attr("SCE_REBOL_ISSUE") = 13;
	current.attr("SCE_REBOL_MONEY") = 12;
	current.attr("SCE_REBOL_NUMBER") = 8;
	current.attr("SCE_REBOL_OPERATOR") = 4;
	current.attr("SCE_REBOL_PAIR") = 9;
	current.attr("SCE_REBOL_PREFACE") = 3;
	current.attr("SCE_REBOL_QUOTEDSTRING") = 6;
	current.attr("SCE_REBOL_TAG") = 14;
	current.attr("SCE_REBOL_TIME") = 19;
	current.attr("SCE_REBOL_TUPLE") = 10;
	current.attr("SCE_REBOL_URL") = 17;
	current.attr("SCE_REBOL_WORD") = 21;
	current.attr("SCE_REBOL_WORD2") = 22;
	current.attr("SCE_REBOL_WORD3") = 23;
	current.attr("SCE_REBOL_WORD4") = 24;
	current.attr("SCE_REBOL_WORD5") = 25;
	current.attr("SCE_REBOL_WORD6") = 26;
	current.attr("SCE_REBOL_WORD7") = 27;
	current.attr("SCE_REBOL_WORD8") = 28;
	current.attr("SCE_SCRIPTOL_CHARACTER") = 8;
	current.attr("SCE_SCRIPTOL_CLASSNAME") = 14;
	current.attr("SCE_SCRIPTOL_COMMENTBLOCK") = 5;
	current.attr("SCE_SCRIPTOL_COMMENTLINE") = 2;
	current.attr("SCE_SCRIPTOL_CSTYLE") = 4;
	current.attr("SCE_SCRIPTOL_DEFAULT") = 0;
	current.attr("SCE_SCRIPTOL_IDENTIFIER") = 12;
	current.attr("SCE_SCRIPTOL_KEYWORD") = 10;
	current.attr("SCE_SCRIPTOL_NUMBER") = 6;
	current.attr("SCE_SCRIPTOL_OPERATOR") = 11;
	current.attr("SCE_SCRIPTOL_PERSISTENT") = 3;
	current.attr("SCE_SCRIPTOL_PREPROCESSOR") = 15;
	current.attr("SCE_SCRIPTOL_STRING") = 7;
	current.attr("SCE_SCRIPTOL_STRINGEOL") = 9;
	current.attr("SCE_SCRIPTOL_TRIPLE") = 13;
	current.attr("SCE_SCRIPTOL_WHITE") = 1;
	current.attr("SCE_SH_BACKTICKS") = 11;
	current.attr("SCE_SH_CHARACTER") = 6;
	current.attr("SCE_SH_COMMENTLINE") = 2;
	current.attr("SCE_SH_DEFAULT") = 0;
	current.attr("SCE_SH_ERROR") = 1;
	current.attr("SCE_SH_HERE_DELIM") = 12;
	current.attr("SCE_SH_HERE_Q") = 13;
	current.attr("SCE_SH_IDENTIFIER") = 8;
	current.attr("SCE_SH_NUMBER") = 3;
	current.attr("SCE_SH_OPERATOR") = 7;
	current.attr("SCE_SH_PARAM") = 10;
	current.attr("SCE_SH_SCALAR") = 9;
	current.attr("SCE_SH_STRING") = 5;
	current.attr("SCE_SH_WORD") = 4;
	current.attr("SCE_SN_CODE") = 1;
	current.attr("SCE_SN_COMMENTLINE") = 2;
	current.attr("SCE_SN_COMMENTLINEBANG") = 3;
	current.attr("SCE_SN_DEFAULT") = 0;
	current.attr("SCE_SN_IDENTIFIER") = 11;
	current.attr("SCE_SN_NUMBER") = 4;
	current.attr("SCE_SN_OPERATOR") = 10;
	current.attr("SCE_SN_PREPROCESSOR") = 9;
	current.attr("SCE_SN_REGEXTAG") = 13;
	current.attr("SCE_SN_SIGNAL") = 14;
	current.attr("SCE_SN_STRING") = 6;
	current.attr("SCE_SN_STRINGEOL") = 12;
	current.attr("SCE_SN_USER") = 19;
	current.attr("SCE_SN_WORD") = 5;
	current.attr("SCE_SN_WORD2") = 7;
	current.attr("SCE_SN_WORD3") = 8;
	current.attr("SCE_SQL_CHARACTER") = 7;
	current.attr("SCE_SQL_COMMENT") = 1;
	current.attr("SCE_SQL_COMMENTDOC") = 3;
	current.attr("SCE_SQL_COMMENTDOCKEYWORD") = 17;
	current.attr("SCE_SQL_COMMENTDOCKEYWORDERROR") = 18;
	current.attr("SCE_SQL_COMMENTLINE") = 2;
	current.attr("SCE_SQL_COMMENTLINEDOC") = 15;
	current.attr("SCE_SQL_DEFAULT") = 0;
	current.attr("SCE_SQL_IDENTIFIER") = 11;
	current.attr("SCE_SQL_NUMBER") = 4;
	current.attr("SCE_SQL_OPERATOR") = 10;
	current.attr("SCE_SQL_SQLPLUS") = 8;
	current.attr("SCE_SQL_SQLPLUS_COMMENT") = 13;
	current.attr("SCE_SQL_SQLPLUS_PROMPT") = 9;
	current.attr("SCE_SQL_STRING") = 6;
	current.attr("SCE_SQL_USER1") = 19;
	current.attr("SCE_SQL_USER2") = 20;
	current.attr("SCE_SQL_USER3") = 21;
	current.attr("SCE_SQL_USER4") = 22;
	current.attr("SCE_SQL_WORD") = 5;
	current.attr("SCE_SQL_WORD2") = 16;
	current.attr("SCE_ST_ASSIGN") = 14;
	current.attr("SCE_ST_BINARY") = 5;
	current.attr("SCE_ST_BOOL") = 6;
	current.attr("SCE_ST_CHARACTER") = 15;
	current.attr("SCE_ST_COMMENT") = 3;
	current.attr("SCE_ST_DEFAULT") = 0;
	current.attr("SCE_ST_GLOBAL") = 10;
	current.attr("SCE_ST_KWSEND") = 13;
	current.attr("SCE_ST_NIL") = 9;
	current.attr("SCE_ST_NUMBER") = 2;
	current.attr("SCE_ST_RETURN") = 11;
	current.attr("SCE_ST_SELF") = 7;
	current.attr("SCE_ST_SPECIAL") = 12;
	current.attr("SCE_ST_SPEC_SEL") = 16;
	current.attr("SCE_ST_STRING") = 1;
	current.attr("SCE_ST_SUPER") = 8;
	current.attr("SCE_ST_SYMBOL") = 4;
	current.attr("SCE_T3_BLOCK_COMMENT") = 3;
	current.attr("SCE_T3_DEFAULT") = 0;
	current.attr("SCE_T3_D_STRING") = 10;
	current.attr("SCE_T3_HTML_DEFAULT") = 15;
	current.attr("SCE_T3_HTML_STRING") = 16;
	current.attr("SCE_T3_HTML_TAG") = 14;
	current.attr("SCE_T3_IDENTIFIER") = 8;
	current.attr("SCE_T3_KEYWORD") = 6;
	current.attr("SCE_T3_LIB_DIRECTIVE") = 12;
	current.attr("SCE_T3_LINE_COMMENT") = 4;
	current.attr("SCE_T3_MSG_PARAM") = 13;
	current.attr("SCE_T3_NUMBER") = 7;
	current.attr("SCE_T3_OPERATOR") = 5;
	current.attr("SCE_T3_PREPROCESSOR") = 2;
	current.attr("SCE_T3_S_STRING") = 9;
	current.attr("SCE_T3_USER1") = 17;
	current.attr("SCE_T3_USER2") = 18;
	current.attr("SCE_T3_USER3") = 19;
	current.attr("SCE_T3_X_DEFAULT") = 1;
	current.attr("SCE_T3_X_STRING") = 11;
	current.attr("SCE_TEX_COMMAND") = 4;
	current.attr("SCE_TEX_DEFAULT") = 0;
	current.attr("SCE_TEX_GROUP") = 2;
	current.attr("SCE_TEX_SPECIAL") = 1;
	current.attr("SCE_TEX_SYMBOL") = 3;
	current.attr("SCE_TEX_TEXT") = 5;
	current.attr("SCE_VHDL_ATTRIBUTE") = 10;
	current.attr("SCE_VHDL_COMMENT") = 1;
	current.attr("SCE_VHDL_COMMENTLINEBANG") = 2;
	current.attr("SCE_VHDL_DEFAULT") = 0;
	current.attr("SCE_VHDL_IDENTIFIER") = 6;
	current.attr("SCE_VHDL_KEYWORD") = 8;
	current.attr("SCE_VHDL_NUMBER") = 3;
	current.attr("SCE_VHDL_OPERATOR") = 5;
	current.attr("SCE_VHDL_STDFUNCTION") = 11;
	current.attr("SCE_VHDL_STDOPERATOR") = 9;
	current.attr("SCE_VHDL_STDPACKAGE") = 12;
	current.attr("SCE_VHDL_STDTYPE") = 13;
	current.attr("SCE_VHDL_STRING") = 4;
	current.attr("SCE_VHDL_STRINGEOL") = 7;
	current.attr("SCE_VHDL_USERWORD") = 14;
	current.attr("SCE_V_COMMENT") = 1;
	current.attr("SCE_V_COMMENTLINE") = 2;
	current.attr("SCE_V_COMMENTLINEBANG") = 3;
	current.attr("SCE_V_DEFAULT") = 0;
	current.attr("SCE_V_IDENTIFIER") = 11;
	current.attr("SCE_V_NUMBER") = 4;
	current.attr("SCE_V_OPERATOR") = 10;
	current.attr("SCE_V_PREPROCESSOR") = 9;
	current.attr("SCE_V_STRING") = 6;
	current.attr("SCE_V_STRINGEOL") = 12;
	current.attr("SCE_V_USER") = 19;
	current.attr("SCE_V_WORD") = 5;
	current.attr("SCE_V_WORD2") = 7;
	current.attr("SCE_V_WORD3") = 8;
	current.attr("SCE_YAML_COMMENT") = 1;
	current.attr("SCE_YAML_DEFAULT") = 0;
	current.attr("SCE_YAML_DOCUMENT") = 6;
	current.attr("SCE_YAML_ERROR") = 8;
	current.attr("SCE_YAML_IDENTIFIER") = 2;
	current.attr("SCE_YAML_KEYWORD") = 3;
	current.attr("SCE_YAML_NUMBER") = 4;
	current.attr("SCE_YAML_REFERENCE") = 5;
	current.attr("SCE_YAML_TEXT") = 7;
	current.attr("SCFIND_MATCHCASE") = 4;
	current.attr("SCFIND_POSIX") = 0x00400000;
	current.attr("SCFIND_REGEXP") = 0x00200000;
	current.attr("SCFIND_WHOLEWORD") = 2;
	current.attr("SCFIND_WORDSTART") = 0x00100000;
	current.attr("SCI_LEXER_START") = 4000;
	current.attr("SCI_OPTIONAL_START") = 3000;
	current.attr("SCI_START") = 2000;
	current.attr("SCK_ADD") = 310;
	current.attr("SCK_BACK") = 8;
	current.attr("SCK_DELETE") = 308;
	current.attr("SCK_DIVIDE") = 312;
	current.attr("SCK_DOWN") = 300;
	current.attr("SCK_END") = 305;
	current.attr("SCK_ESCAPE") = 7;
	current.attr("SCK_HOME") = 304;
	current.attr("SCK_INSERT") = 309;
	current.attr("SCK_LEFT") = 302;
	current.attr("SCK_NEXT") = 307;
	current.attr("SCK_PRIOR") = 306;
	current.attr("SCK_RETURN") = 13;
	current.attr("SCK_RIGHT") = 303;
	current.attr("SCK_SUBTRACT") = 311;
	current.attr("SCK_TAB") = 9;
	current.attr("SCK_UP") = 301;
	current.attr("SCLEX_ADA") = 20;
	current.attr("SCLEX_APDL") = 61;
	current.attr("SCLEX_ASM") = 34;
	current.attr("SCLEX_ASN1") = 63;
	current.attr("SCLEX_AU3") = 60;
	current.attr("SCLEX_AUTOMATIC") = 1000;
	current.attr("SCLEX_AVE") = 19;
	current.attr("SCLEX_BAAN") = 31;
	current.attr("SCLEX_BASH") = 62;
	current.attr("SCLEX_BATCH") = 12;
	current.attr("SCLEX_BLITZBASIC") = 66;
	current.attr("SCLEX_BULLANT") = 27;
	current.attr("SCLEX_CAML") = 65;
	current.attr("SCLEX_CLW") = 45;
	current.attr("SCLEX_CLWNOCASE") = 46;
	current.attr("SCLEX_CONF") = 17;
	current.attr("SCLEX_CONTAINER") = 0;
	current.attr("SCLEX_CPP") = 3;
	current.attr("SCLEX_CPPNOCASE") = 35;
	current.attr("SCLEX_CSOUND") = 74;
	current.attr("SCLEX_CSS") = 38;
	current.attr("SCLEX_DIFF") = 16;
	current.attr("SCLEX_EIFFEL") = 23;
	current.attr("SCLEX_EIFFELKW") = 24;
	current.attr("SCLEX_ERLANG") = 53;
	current.attr("SCLEX_ERRORLIST") = 10;
	current.attr("SCLEX_ESCRIPT") = 41;
	current.attr("SCLEX_F77") = 37;
	current.attr("SCLEX_FLAGSHIP") = 73;
	current.attr("SCLEX_FORTH") = 52;
	current.attr("SCLEX_FORTRAN") = 36;
	current.attr("SCLEX_FREEBASIC") = 75;
	current.attr("SCLEX_GUI4CLI") = 58;
	current.attr("SCLEX_HASKELL") = 68;
	current.attr("SCLEX_HTML") = 4;
	current.attr("SCLEX_KIX") = 57;
	current.attr("SCLEX_LATEX") = 14;
	current.attr("SCLEX_LISP") = 21;
	current.attr("SCLEX_LOT") = 47;
	current.attr("SCLEX_LOUT") = 40;
	current.attr("SCLEX_LUA") = 15;
	current.attr("SCLEX_MAKEFILE") = 11;
	current.attr("SCLEX_MATLAB") = 32;
	current.attr("SCLEX_METAPOST") = 50;
	current.attr("SCLEX_MMIXAL") = 44;
	current.attr("SCLEX_MSSQL") = 55;
	current.attr("SCLEX_NNCRONTAB") = 26;
	current.attr("SCLEX_NSIS") = 43;
	current.attr("SCLEX_NULL") = 1;
	current.attr("SCLEX_OCTAVE") = 54;
	current.attr("SCLEX_PASCAL") = 18;
	current.attr("SCLEX_PERL") = 6;
	current.attr("SCLEX_PHPSCRIPT") = 69;
	current.attr("SCLEX_POV") = 39;
	current.attr("SCLEX_POWERBASIC") = 51;
	current.attr("SCLEX_PROPERTIES") = 9;
	current.attr("SCLEX_PS") = 42;
	current.attr("SCLEX_PUREBASIC") = 67;
	current.attr("SCLEX_PYTHON") = 2;
	current.attr("SCLEX_REBOL") = 71;
	current.attr("SCLEX_RUBY") = 22;
	current.attr("SCLEX_SCRIPTOL") = 33;
	current.attr("SCLEX_SMALLTALK") = 72;
	current.attr("SCLEX_SPECMAN") = 59;
	current.attr("SCLEX_SQL") = 7;
	current.attr("SCLEX_TADS3") = 70;
	current.attr("SCLEX_TCL") = 25;
	current.attr("SCLEX_TEX") = 49;
	current.attr("SCLEX_VB") = 8;
	current.attr("SCLEX_VBSCRIPT") = 28;
	current.attr("SCLEX_VERILOG") = 56;
	current.attr("SCLEX_VHDL") = 64;
	current.attr("SCLEX_XCODE") = 13;
	current.attr("SCLEX_XML") = 5;
	current.attr("SCLEX_YAML") = 48;
	current.attr("SCMOD_ALT") = 4;
	current.attr("SCMOD_CTRL") = 2;
	current.attr("SCMOD_SHIFT") = 1;
	current.attr("SCWS_INVISIBLE") = 0;
	current.attr("SCWS_VISIBLEAFTERINDENT") = 2;
	current.attr("SCWS_VISIBLEALWAYS") = 1;
	current.attr("SC_CACHE_CARET") = 1;
	current.attr("SC_CACHE_DOCUMENT") = 3;
	current.attr("SC_CACHE_NONE") = 0;
	current.attr("SC_CACHE_PAGE") = 2;
	current.attr("SC_CASE_LOWER") = 2;
	current.attr("SC_CASE_MIXED") = 0;
	current.attr("SC_CASE_UPPER") = 1;
	current.attr("SC_CHARSET_8859_15") = 1000;
	current.attr("SC_CHARSET_ANSI") = 0;
	current.attr("SC_CHARSET_ARABIC") = 178;
	current.attr("SC_CHARSET_BALTIC") = 186;
	current.attr("SC_CHARSET_CHINESEBIG5") = 136;
	current.attr("SC_CHARSET_CYRILLIC") = 1251;
	current.attr("SC_CHARSET_DEFAULT") = 1;
	current.attr("SC_CHARSET_EASTEUROPE") = 238;
	current.attr("SC_CHARSET_GB2312") = 134;
	current.attr("SC_CHARSET_GREEK") = 161;
	current.attr("SC_CHARSET_HANGUL") = 129;
	current.attr("SC_CHARSET_HEBREW") = 177;
	current.attr("SC_CHARSET_JOHAB") = 130;
	current.attr("SC_CHARSET_MAC") = 77;
	current.attr("SC_CHARSET_OEM") = 255;
	current.attr("SC_CHARSET_RUSSIAN") = 204;
	current.attr("SC_CHARSET_SHIFTJIS") = 128;
	current.attr("SC_CHARSET_SYMBOL") = 2;
	current.attr("SC_CHARSET_THAI") = 222;
	current.attr("SC_CHARSET_TURKISH") = 162;
	current.attr("SC_CHARSET_VIETNAMESE") = 163;
	current.attr("SC_CP_DBCS") = 1;
	current.attr("SC_CP_UTF8") = 65001;
	current.attr("SC_CURSORNORMAL") = -1;
	current.attr("SC_CURSORWAIT") = 4;
	current.attr("SC_EOL_CR") = 1;
	current.attr("SC_EOL_CRLF") = 0;
	current.attr("SC_EOL_LF") = 2;
	current.attr("SC_FOLDFLAG_BOX") = 0x0001;
	current.attr("SC_FOLDFLAG_LEVELNUMBERS") = 0x0040;
	current.attr("SC_FOLDFLAG_LINEAFTER_CONTRACTED") = 0x0010;
	current.attr("SC_FOLDFLAG_LINEAFTER_EXPANDED") = 0x0008;
	current.attr("SC_FOLDFLAG_LINEBEFORE_CONTRACTED") = 0x0004;
	current.attr("SC_FOLDFLAG_LINEBEFORE_EXPANDED") = 0x0002;
	current.attr("SC_FOLDLEVELBASE") = 0x400;
	current.attr("SC_FOLDLEVELBOXFOOTERFLAG") = 0x8000;
	current.attr("SC_FOLDLEVELBOXHEADERFLAG") = 0x4000;
	current.attr("SC_FOLDLEVELCONTRACTED") = 0x10000;
	current.attr("SC_FOLDLEVELHEADERFLAG") = 0x2000;
	current.attr("SC_FOLDLEVELNUMBERMASK") = 0x0FFF;
	current.attr("SC_FOLDLEVELUNINDENT") = 0x20000;
	current.attr("SC_FOLDLEVELWHITEFLAG") = 0x1000;
	current.attr("SC_LASTSTEPINUNDOREDO") = 0x100;
	current.attr("SC_MARGIN_NUMBER") = 1;
	current.attr("SC_MARGIN_SYMBOL") = 0;
	current.attr("SC_MARKNUM_FOLDER") = 30;
	current.attr("SC_MARKNUM_FOLDEREND") = 25;
	current.attr("SC_MARKNUM_FOLDERMIDTAIL") = 27;
	current.attr("SC_MARKNUM_FOLDEROPEN") = 31;
	current.attr("SC_MARKNUM_FOLDEROPENMID") = 26;
	current.attr("SC_MARKNUM_FOLDERSUB") = 29;
	current.attr("SC_MARKNUM_FOLDERTAIL") = 28;
	current.attr("SC_MARK_ARROW") = 2;
	current.attr("SC_MARK_ARROWDOWN") = 6;
	current.attr("SC_MARK_ARROWS") = 24;
	current.attr("SC_MARK_BACKGROUND") = 22;
	current.attr("SC_MARK_BOXMINUS") = 14;
	current.attr("SC_MARK_BOXMINUSCONNECTED") = 15;
	current.attr("SC_MARK_BOXPLUS") = 12;
	current.attr("SC_MARK_BOXPLUSCONNECTED") = 13;
	current.attr("SC_MARK_CHARACTER") = 10000;
	current.attr("SC_MARK_CIRCLE") = 0;
	current.attr("SC_MARK_CIRCLEMINUS") = 20;
	current.attr("SC_MARK_CIRCLEMINUSCONNECTED") = 21;
	current.attr("SC_MARK_CIRCLEPLUS") = 18;
	current.attr("SC_MARK_CIRCLEPLUSCONNECTED") = 19;
	current.attr("SC_MARK_DOTDOTDOT") = 23;
	current.attr("SC_MARK_EMPTY") = 5;
	current.attr("SC_MARK_FULLRECT") = 26;
	current.attr("SC_MARK_LCORNER") = 10;
	current.attr("SC_MARK_LCORNERCURVE") = 16;
	current.attr("SC_MARK_MINUS") = 7;
	current.attr("SC_MARK_PIXMAP") = 25;
	current.attr("SC_MARK_PLUS") = 8;
	current.attr("SC_MARK_ROUNDRECT") = 1;
	current.attr("SC_MARK_SHORTARROW") = 4;
	current.attr("SC_MARK_SMALLRECT") = 3;
	current.attr("SC_MARK_TCORNER") = 11;
	current.attr("SC_MARK_TCORNERCURVE") = 17;
	current.attr("SC_MARK_VLINE") = 9;
	current.attr("SC_MASK_FOLDERS") = 0xFE000000;
	current.attr("SC_MODEVENTMASKALL") = 0x1FFF;
	current.attr("SC_MOD_BEFOREDELETE") = 0x800;
	current.attr("SC_MOD_BEFOREINSERT") = 0x400;
	current.attr("SC_MOD_CHANGEFOLD") = 0x8;
	current.attr("SC_MOD_CHANGEMARKER") = 0x200;
	current.attr("SC_MOD_CHANGESTYLE") = 0x4;
	current.attr("SC_MOD_DELETETEXT") = 0x2;
	current.attr("SC_MOD_INSERTTEXT") = 0x1;
	current.attr("SC_MULTILINEUNDOREDO") = 0x1000;
	current.attr("SC_MULTISTEPUNDOREDO") = 0x80;
	current.attr("SC_PERFORMED_REDO") = 0x40;
	current.attr("SC_PERFORMED_UNDO") = 0x20;
	current.attr("SC_PERFORMED_USER") = 0x10;
	current.attr("SC_PRINT_BLACKONWHITE") = 2;
	current.attr("SC_PRINT_COLOURONWHITE") = 3;
	current.attr("SC_PRINT_COLOURONWHITEDEFAULTBG") = 4;
	current.attr("SC_PRINT_INVERTLIGHT") = 1;
	current.attr("SC_PRINT_NORMAL") = 0;
	current.attr("SC_SEL_LINES") = 2;
	current.attr("SC_SEL_RECTANGLE") = 1;
	current.attr("SC_SEL_STREAM") = 0;
	current.attr("SC_TIME_FOREVER") = 10000000;
	current.attr("SC_WRAPVISUALFLAGLOC_DEFAULT") = 0x0000;
	current.attr("SC_WRAPVISUALFLAGLOC_END_BY_TEXT") = 0x0001;
	current.attr("SC_WRAPVISUALFLAGLOC_START_BY_TEXT") = 0x0002;
	current.attr("SC_WRAPVISUALFLAG_END") = 0x0001;
	current.attr("SC_WRAPVISUALFLAG_NONE") = 0x0000;
	current.attr("SC_WRAPVISUALFLAG_START") = 0x0002;
	current.attr("SC_WRAP_CHAR") = 2;
	current.attr("SC_WRAP_NONE") = 0;
	current.attr("SC_WRAP_WORD") = 1;
	current.attr("STYLE_BRACEBAD") = 35;
	current.attr("STYLE_BRACELIGHT") = 34;
	current.attr("STYLE_CONTROLCHAR") = 36;
	current.attr("STYLE_DEFAULT") = 32;
	current.attr("STYLE_INDENTGUIDE") = 37;
	current.attr("STYLE_LASTPREDEFINED") = 39;
	current.attr("STYLE_LINENUMBER") = 33;
	current.attr("STYLE_MAX") = 127;
	current.attr("VISIBLE_SLOP") = 0x01;
	current.attr("VISIBLE_STRICT") = 0x04;
/*--Autogenerated*/
;
}