//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pn.rc
//
#define ID_RECENTFILES_BLANKER          0
#define IDC_REPLACE_BUTTON              4
#define IDR_TBR_EDIT                    5
#define IDC_REPLACEALL_BUTTON           6
#define IDC_REPLACEINSEL_BUTTON         7
#define IDD_ABOUTBOX                    100
#define IDC_FINDTEXT_COMBO              102
#define IDC_FINDNEXT_BUTTON             103
#define IDC_MATCHWHOLE_CHECK            104
#define IDC_MATCHCASE_CHECK             105
#define IDC_REPLACETEXT_COMBO           106
#define IDC_REGEXP_CHECK                107
#define IDC_UP_RADIO                    113
#define IDC_DOWN_RADIO                  114
#define ID_POS_PANE                     115
#define ID_MOD_PANE                     116
#define ID_INS_PANE                     117
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define ID_EDITOR_WORDWRAP              130
#define ID_EDITOR_COLOURISE             131
#define ID_EDITOR_LINENOS               132
#define IDD_FIND                        168
#define IDR_TABS_POPUP                  169
#define IDR_POPUP_REGEXP                170
#define IDD_REPLACE                     171
#define IDR_POPUP_EDITOR                173
#define IDB_EDITOR                      203
#define IDD_GOTO                        204
#define ID_MRUFILE_BASE                 205
#define ID_VIEW_CHANGESCHEME            221
#define ID_VIEW_SCHEMES                 222
#define IDR_POPUP_REGEXPM               226
#define ID_REGEXP_TAGGEDEXPRESSION1     227
#define ID_REGEXP_TAGGEDEXPRESSION2     228
#define ID_REGEXP_TAGGEDEXPRESSION3     229
#define ID_REGEXP_TAGGEDEXPRESSION4     230
#define ID_REGEXP_TAGGEDEXPRESSION5     231
#define ID_REGEXP_TAGGEDEXPRESSION6     232
#define ID_REGEXP_TAGGEDEXPRESSION7     233
#define ID_REGEXP_TAGGEDEXPRESSION8     234
#define ID_REGEXP_TAGGEDEXPRESSION9     235
#define ID_VIEW_TOOLBARS                236
#define ID_TOOLBARS_TOOLBAR             237
#define ID_VIEW_TOOLBAR_EDIT            238
#define ID_VIEW_LINENUMBERS             240
#define ID_VIEW_SYNTAXHIGHLIGHTING      241
#define ID_VIEW_WORDWRAP                242
#define IDD_OPTIONS                     243
#define IDD_TESTPAGE                    244
#define IDD_PAGE_STYLE                  244
#define ID_TOOLS_OPTIONS                245
#define ID_TOOLS_OPTIONS246             246
#define IDB_TRUETYPE_FONTTYPE           248
#define IDD_TAB_STYLES                  250
#define ID_HELP_WEB_PN                  251
#define ID_HELP_WEB_SF                  252
#define ID_HELP_WEB_SB                  253
#define ID_HELP_REPORTABUG              254
#define IDD_PNSAVE                      423
#define IDD_PAGE_SCHEMES                424
#define IDD_TAB_STYLES1                 425
#define IDD_TAB_KEYWORDS                425
#define IDC_FINDTEXT_DUMMY              1001
#define IDC_REPLACETEXT_DUMMY           1002
#define IDC_GOTOEDIT                    1004
#define IDC_PNSCOMBO                    1005
#define IDC_HELPBTN                     1006
#define IDC_TREE                        1007
#define IDC_PLACEHOLDER                 1008
#define IDC_PROGRESS1                   1009
#define IDC_BUTTON1                     1010
#define IDC_STYLE_FOREBUTTON            1010
#define IDC_EDIT1                       1011
#define IDC_KEYWORDS_KEYWORDTEXT        1011
#define IDC_FONT_COMBO                  1012
#define IDC_FONTSIZE_COMBO              1013
#define IDC_SCHEMECOMBO                 1016
#define IDC_SCHEMELABEL                 1017
#define IDC_STYLES_TREE                 1020
#define IDC_STYLE_BOLDCHECK             1021
#define IDC_STYLE_ITALICCHECK           1022
#define IDC_STYLE_UNDERLINECHECK        1023
#define IDC_STYLE_EOLFILLEDCHECK        1024
#define IDC_STYLE_EXAMPLE               1027
#define IDC_PS_PLACEHOLDER              1029
#define IDC_STYLE_FONTCOMBO             1031
#define IDC_STYLE_SIZECOMBO             1032
#define IDC_BUTTON2                     1033
#define IDC_STYLE_BACKBUTTON            1033
#define IDC_KEYWORDS_RESETBUTTON        1033
#define IDC_STYLE_RESETBTN              1036
#define IDC_STYLE_RESETALLBTN           1037
#define IDC_LIST1                       1039
#define IDC_KEYWORDS_LIST               1039
#define IDC_REPLACETEXT_LABEL           1042
#define IDC_BACKSLASH_CHECK             1043
#define IDC_PNSAVE_SAVEASSTATIC         1056
#define IDC_PNSAVE_TYPECOMBO            1057
#define IDC_MARKALL_BUTTON              21199
#define IDC_SEARCHALL_CHECK             21200
#define IDC_REHELPER_BUTTON             21204
#define IDC_RHELPER_BUTTON              21205
#define IDC_DIRECTION_GROUP             21207
#define ID_EDIT_FINDNEXT                32773
#define ID_EDIT_GOTO                    32774
#define ID_TOOLS_LECRLF                 32777
#define ID_TOOLS_LELF                   32778
#define ID_TOOLS_LECR                   32779
#define ID_TOOLS_LECONVERT              32780
#define ID_BUTTON32781                  32781
#define ID_BOOKMARKS_NUMBERED_SET       32783
#define ID_BOOKMARKS_NUMBERED_JUMP      32784
#define ID_BOOKMARKS_TOGGLE             32786
#define ID_BOOKMARKS_NEXT               32787
#define ID_VIEW_VIEWTABS                32825
#define ID_TAB_CLOSE                    32835
#define ID_VIEW_TABS_TOP                32836
#define ID_VIEW_TABS_BOTTOM             32837
#define ID_REGEXP_ANYCHARACTER          32839
#define ID_REGEXP_CHARACTERINRANGE      32840
#define ID_REGEXP_CHARACTERNOTINRANGE   32841
#define ID_REGEXP_BEGINNINGOFLINE       32842
#define ID_REGEXP_ENDOFLINE             32843
#define ID_REGEXP_TAGGEDEXPRESSSION     32844
#define ID_REGEXP_NOT                   32845
#define ID_REGEXP_OR                    32846
#define ID_REGEXP_0ORMOREMATCHES        32847
#define ID_REGEXP_1ORMOREMATCHES        32848
#define ID_REGEXP_GROUP                 32849
#define ID_EDIT_DELETE                  32862
#define ID_EDIT_INDENT                  32863
#define ID_EDIT_UNINDENT                32864
#define IDC_FINDTEXT_LABEL              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
