//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pn.rc
//
#define IDOK2                           3
#define IDC_REPLACE_BUTTON              4
#define IDR_TBR_EDIT                    5
#define IDR_POPUP_TABS                  5
#define IDC_REPLACEALL_BUTTON           6
#define IDC_REPLACEINSEL_BUTTON         7
#define IDD_PAGESETUP                   12
#define IDC_HEADERTEXT                  30
#define IDC_FOOTERTEXT                  31
#define ID_MRUFILE_BASE                 50
#define ID_MRUFILE_MAX                  99
#define IDD_ABOUTBOX                    100
#define IDC_FINDTEXT_COMBO              102
#define IDC_FINDNEXT_BUTTON             103
#define IDC_MATCHWHOLE_CHECK            104
#define IDC_MATCHCASE_CHECK             105
#define IDC_REPLACETEXT_COMBO           106
#define IDC_REGEXP_CHECK                107
#define IDC_FINDWHERE_COMBO             108
#define IDC_FINDTYPE_COMBO              109
#define IDC_UP_RADIO                    113
#define IDC_DOWN_RADIO                  114
#define ID_POS_PANE                     115
#define ID_MOD_PANE                     116
#define ID_INS_PANE                     117
#define ID_ENC_PANE                     118
#define ID_LINEENDS_PANE                119
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define ID_EDITOR_WORDWRAP              130
#define ID_EDITOR_COLOURISE             131
#define ID_EDITOR_LINENOS               132
#define ID_EDITOR_OUTPUTWND             133
#define IDS_ABOUTVERSIONSTRING          133
#define IDS_TOOLFORMATSTRINGS           134
#define IDS_PROJECTNOPROPS              134
#define IDS_PATTERNFORMATSTRINGS        135
#define ID_FILE_NEW_PROJECT             136
#define ID_FILE_NEW_WORKSPACE           137
#define IDS_SAVEREADONLY                138
#define IDS_SAVEREADONLYFAIL            139
#define IDS_PROPSTITLE                  140
#define IDS_FINDNOTFOUND                141
#define IDS_NREPLACEMENTS               142
#define IDS_FINDLOOPED                  143
#define IDS_BROWSEFINDROOT              144
#define IDS_GLOBALOUTPUT                145
#define IDS_RECENTFILES                 146
#define IDS_RECENTPROJECTS              147
#define IDS_PROJECTS_DEFAULTTEMPLATE    148
#define IDS_CHANGESCHEME                149
#define IDS_NEW                         150
#define IDS_NEWPROJECTGROUP             151
#define IDS_OPENPROJECTDLGTITLE         152
#define IDS_SAVESOMETHING               153
#define IDS_MODIFIEDELSEWHERE           154
#define IDS_FILENOLONGEREXISTS          155
#define IDS_WORKSPACEFILES              156
#define IDS_PROJECTGROUPFILES           157
#define IDS_ALLFILES                    158
#define IDS_ALLPROJECTFILES             159
#define IDS_SELLENGTH                   160
#define IDS_RECTSEL                     161
#define IDS_FILTERSELECTION             162
#define IDS_TOOL_EXITCODE               163
#define IDS_TOOL_TIMETAKEN              164
#define IDS_SAVE_CHANGES                165
#define IDS_PATHNOTINMAGICFOLDER        166
#define IDI_TEXTCLIPS                   167
#define IDS_CANTCREATEFILE              167
#define IDS_STRING168                   168
#define IDS_CANTOPENFILE                168
#define IDS_CREATEPROJECTFOLDER         169
#define IDR_POPUP_REGEXP                170
#define IDS_CREATEPROJECTFOLDERFAILED   170
#define IDS_CURRENTFILE                 171
#define IDS_CURRENTFOLDER               172
#define IDR_POPUP_EDITOR                173
#define IDS_CURRENTPROJECTFILES         173
#define IDS_FILETOOBIG                  174
#define IDS_INVALIDREGEX                175
#define IDS_UPDATEAVAIL                 176
#define IDS_DOWNLOADNOW                 177
#define IDS_REMINDMELATER               178
#define IDS_DONOTDOWNLOAD               179
#define IDS_ALLOPENFILES                180
#define IDS_ALLFOUND                    181
#define IDS_SAVEANDREMOVE               182
#define IDS_DONOTREMOVE                 183
#define IDS_REMOVE                      184
#define IDS_SAVEBEFOREREMOVEQUESTION    185
#define IDS_QSAVEPROJBEFOREREMOVE       185
#define IDB_EDITOR                      203
#define IDD_GOTO                        204
#define IDD_INPUTBOX                    204
#define ID_VIEW_CHANGESCHEME            221
#define ID_VIEW_SCHEMES                 222
#define IDR_POPUP_REGEXPM               226
#define ID_REGEXP_TAGGEDEXPRESSION1     227
#define ID_REGEXP_TAGGEDEXPRESSION2     228
#define ID_REGEXP_TAGGEDEXPRESSION3     229
#define ID_REGEXP_TAGGEDEXPRESSION4     230
#define ID_REGEXP_TAGGEDEXPRESSION5     231
#define ID_REGEXP_TAGGEDEXPRESSION6     232
#define ID_REGEXP_TAGGEDEXPRESSION7     233
#define ID_REGEXP_TAGGEDEXPRESSION8     234
#define ID_REGEXP_TAGGEDEXPRESSION9     235
#define ID_VIEW_TOOLBARS                236
#define ID_TOOLBARS_TOOLBAR             237
#define ID_VIEW_TOOLBAR_EDIT            238
#define ID_VIEW_LINENUMBERS             240
#define ID_VIEW_SYNTAXHIGHLIGHTING      241
#define ID_VIEW_WORDWRAP                242
#define IDD_OPTIONS                     243
#define IDD_TESTPAGE                    244
#define IDD_PAGE_STYLE                  244
#define ID_TOOLS_OPTIONS                245
#define ID_TOOLS_OPTIONS246             246
#define IDB_TRUETYPE_FONTTYPE           248
#define IDD_TAB_STYLES                  250
#define ID_HELP_WEB_PN                  251
#define ID_HELP_WEB_SF                  252
#define ID_HELP_WEB_SB                  253
#define ID_HELP_REPORTABUG              254
#define IDD_TOOLEDITOR                  255
#define IDR_POPUP_OUTPUT                257
#define ID_PROJECT_DELETE               258
#define ID_OUTPUT_CLEAR                 259
#define ID_OUTPUT_HIDE                  260
#define ID_TOOLS_USETABS                261
#define IDD_SMARTSTARTEDITOR            262
#define ID_FILE_REVERT                  263
#define ID_VIEW_INDIVIDUALOUTPUT        264
#define ID_FILE_EXPORT                  265
#define ID_EXPORT_RTF                   266
#define ID_EDIT_CLIPBOARDSWAP           267
#define ID_VIEW_COLLAPSEALLFOLDS        268
#define ID_VIEW_EXPANDALLFOLDS          269
#define ID_VIEW_FOLDING                 270
#define ID_COLLAPSEALLFOLDS_TOGGLEFOLD  271
#define ID_VIEW_TOGGLEFOLD              272
#define ID_EDIT_SELECTALL               273
#define ID_HELP_WEB_SR                  275
#define IDR_TBR_SCHEME                  276
#define IDR_TOOLBAR1                    278
#define IDR_TBR_FINDCOMBO               278
#define IDR_TBR_FIND                    278
#define IDB_FINDTOOLBAR                 280
#define IDB_TBFIND24                    280
#define IDR_FINDBAR_DDMENU              281
#define IDR_POPUP_FINDBARDD             281
#define ID_FINDBAR_SEARCHGOOGLE         282
#define ID_FINDBAR_SEARCHGOOGLEGROUPS   283
#define IDI_ICON1                       284
#define IDR_MENU1                       285
#define IDR_POPUP_PROJECTFILE           285
#define ID_PROJECT_REMOVE               286
#define ID_PROJECT_OPEN                 287
#define ID_PROJECT_ADDFILES             288
#define ID_FILE_OPENPROJECT             289
#define IDR_POPUP_PROJECTFOLDER         290
#define ID_DUMMY_ADDFILES               291
#define ID_DUMMY_DELETE                 292
#define ID_PROJECT_ADDFOLDER            293
#define IDR_POPUP_PROJECT               294
#define ID_DUMMY_ADDFILES295            295
#define ID_DUMMY_ADDFOLDER              296
#define ID_PROJECT_REMOVEPROJECT        297
#define ID_PROJECT_DELETEPROJECT        298
#define ID_PROJECT_OPENALLFILES         299
#define IDI_ICON2                       300
#define IDI_PROJECTS                    300
#define ID_FILE_CLOSEWORKSPACE          301
#define ID_VIEW_TOOLBARS_FIND           302
#define ID_VIEW_TOOLBARS_SCHEMES        303
#define ID_VIEW_WINDOWS                 304
#define IDR_POPUP_WORKSPACE             307
#define ID_WORKSPACE_NEWPROJECT         308
#define ID_WORKSPACE_ADDPROJECT         309
#define IDI_PROJECTFOLDER               310
#define IDI_WORKSPACE                   311
#define IDI_ICON3                       312
#define IDI_BADPROJECT                  312
#define IDR_POPUP_HEADERFOOTER          314
#define IDR_POPUP_PROJECTMFOLDER        315
#define IDR_TOOLBAR2                    316
#define IDR_TBR_PROJECTS                316
#define IDB_ABOUT                       319
#define IDD_FILEPROPERTIES              320
#define ID_MRUPROJECT_BASE              321
#define IDD_JUMPTO                      321
#define IDB_TAGTYPES                    322
#define IDD_MAGICFOLDERWIZ1             324
#define IDB_TBMAINDIS                   327
#define IDI_MAGICFOLDER                 328
#define IDD_PAGE_FILEASSO               329
#define IDD_FILEASSOC_INFO              330
#define IDD_PNOPEN                      331
#define IDD_PROJPROPS                   332
#define IDD_DIALOG1                     333
#define IDD_TOOLCONSOLEIOPAGE           333
#define IDS_INDIVIDUALOUTPUT            335
#define IDS_OUTPUTSUPPORT               336
#define IDD_NEWPROJECT                  336
#define IDS_TOOLS_VARSTRINGS            337
#define IDS_TOOLS_SELWORKINGFOLDER      338
#define IDS_PROJECTGROUP                339
#define ID_MRUPROJECT_MAX               340
#define IDS_PROJECT                     340
#define IDS_DEFAULTSTATUS               341
#define IDS_FIND                        342
#define IDB_BITMAP1                     342
#define IDB_REDCLOSE                    342
#define IDS_MODIFIED                    343
#define IDI_OUTPUT                      343
#define IDI_ICON4                       344
#define IDI_FINDINFILES                 344
#define IDI_CTAGS                       345
#define IDR_POPUP_CTAGS                 346
#define IDI_SCRIPTS                     346
#define IDR_POPUP_FINDRESULT            347
#define IDR_POPUP_REMOVEPROJECT         347
#define IDB_TBMAIN24                    348
#define IDB_TBEDIT24                    349
#define IDD_TEXTCLIPEDITOR              350
#define IDI_TASKDLG_ARROW_HOT           352
#define IDI_TASKDLG_ARROW_NORMAL        353
#define IDI_TASKDLG_CHEVRON_LESS        354
#define IDI_ICON6                       355
#define IDI_TASKDLG_CHEVRON_MORE        355
#define IDI_OPENFILES                   359
#define IDB_BITMAP2                     360
#define IDB_OPENFILES                   360
#define IDI_ICON5                       361
#define IDI_BROWSER                     361
#define IDC_MARGIN                      400
#define IDD_PNSAVE                      423
#define IDD_PAGE_SCHEMES                424
#define IDD_TAB_STYLES1                 425
#define IDD_TAB_KEYWORDS                425
#define IDD_PAGE_TOOLS                  426
#define IDD_PAGE_GENERAL                427
#define IDD_PAGE_SMARTSTART             428
#define IDD_PAGE_NEWFILES               428
#define IDD_PAGE_VISUALHELP             429
#define IDD_TAB_MISC                    430
#define IDD_PAGE_AFILES                 431
#define IDD_AFILEEDITOR                 432
#define IDD_PAGE_EDITDEFS               433
#define IDD_PAGE_CONF                   434
#define IDD_MAGICFOLDERWIZ2             435
#define IDD_FINDEX                      436
#define IDD_PAGE_DIALOGS                437
#define IDD_PAGE_FILETYPES              438
#define IDD_FILETYPEEDITOR              439
#define IDD_PAGE_KEYBOARD               440
#define IDD_PAGE_AUTOCOMPLETE           441
#define IDD_PAGE_STYLECLASSES           442
#define IDD_PAGE_KEYWORDTEXTCLIPS       443
#define IDD_PAGE_EXTENSIONS             444
#define IDC_FINDTEXT_DUMMY              1001
#define IDC_REPLACETEXT_DUMMY           1002
#define IDC_FINDTYPE_DUMMY              1003
#define IDC_GOTOEDIT                    1004
#define IDC_THEEDIT                     1004
#define IDC_FINDWHERE_DUMMY             1004
#define IDC_FINDWHERE_DUMM              1004
#define IDC_PNSCOMBO                    1005
#define IDC_HELPBTN                     1006
#define IDC_TREE                        1007
#define IDC_PLACEHOLDER                 1008
#define IDC_PROGRESS1                   1009
#define IDC_BUTTON1                     1010
#define IDC_STYLE_FOREBUTTON            1010
#define IDC_TOOLS_ADDBUTTON             1010
#define IDC_TE_COMMANDBUTTON            1010
#define IDC_SMARTSTART_REMOVE           1010
#define IDC_SMARTSTART_REMOVEBUTTON     1010
#define IDC_OPT_LINELIGHTBUTTON         1010
#define IDC_ADD                         1010
#define IDC_BROWSE                      1010
#define IDC_KB_REMOVE                   1010
#define IDC_EDIT1                       1011
#define IDC_KEYWORDS_KEYWORDTEXT        1011
#define IDC_TOOLS_EDITBUTTON            1011
#define IDC_TE_NAMEEDIT                 1011
#define IDC_OPT_TABWIDTHEDIT            1011
#define IDC_PHRASEEDIT                  1011
#define IDC_OPT_LLCOLUMNEDIT            1011
#define IDC_STYLE_SELFOREBUTTON         1011
#define IDC_AFILE_STARTTEXT             1011
#define IDC_FILEPROP_TABWIDTH           1011
#define IDC_JUMPTOTEXT                  1011
#define IDC_EXTENSION                   1011
#define IDC_PROJNAMEEDIT                1011
#define IDC_KB_ADD                      1011
#define IDC_AUTOCOMPLETECHARSTEXT       1011
#define IDC_FONT_COMBO                  1012
#define IDC_TOOLS_REMOVEBUTTON          1012
#define IDC_TE_BROWSEBUTTON             1012
#define IDC_TE_DIRBUTTON                1012
#define IDC_STYLE_SELBACKBUTTON         1012
#define IDC_AFILE_STARTTEXT2            1012
#define IDC_AFILE_OTHERTEXT             1012
#define IDC_FILETYPE_MATCH              1012
#define IDC_SHORTCUT_EDIT               1012
#define IDC_FONTSIZE_COMBO              1013
#define IDC_STYLE_IGCOLBUTTON           1013
#define IDC_HINT_EDIT                   1013
#define IDC_STYLE_SELBACKBUTTON2        1014
#define IDC_STYLE_IGCOLBUTTON2          1015
#define IDC_SCHEMECOMBO                 1016
#define IDC_SCHEMELABEL                 1017
#define IDC_STYLES_TREE                 1020
#define IDC_STYLE_BOLDCHECK             1021
#define IDC_STYLE_ITALICCHECK           1022
#define IDC_STYLE_UNDERLINECHECK        1023
#define IDC_STYLE_EOLFILLEDCHECK        1024
#define IDC_STYLE_EXAMPLE               1027
#define IDC_PS_PLACEHOLDER              1029
#define IDC_STYLE_FONTCOMBO             1031
#define IDC_STYLE_SIZECOMBO             1032
#define IDC_BUTTON2                     1033
#define IDC_STYLE_BACKBUTTON            1033
#define IDC_KEYWORDS_RESETBUTTON        1033
#define IDC_TOOLS_MOVEUPBUTTON          1033
#define IDC_TE_CLEARBUTTON              1033
#define IDC_SMARTSTART_EDITBUTTON       1033
#define IDC_OPT_LLCOLORBUTTON           1033
#define IDC_REMOVE                      1033
#define IDC_KEYWORDS_SORTBUTTON         1034
#define IDC_TOOLS_MOVEDOWNBUTTON        1034
#define IDC_SMARTSTART_ADDBUTTON        1034
#define IDC_STYLE_RESETBTN              1036
#define IDC_STYLE_RESETALLBTN           1037
#define IDC_STYLE_LOADPRESETBUTTON      1038
#define IDC_LIST1                       1039
#define IDC_KEYWORDS_LIST               1039
#define IDC_LIST                        1039
#define IDC_SMARTSTART_LIST             1039
#define IDC_JUMPTOLIST                  1039
#define IDC_FILEASSO_LIST               1039
#define IDC_LISTPROPS                   1039
#define IDC_LISTPROJECTS                1039
#define IDC_KB_COMMANDS                 1039
#define IDC_STYLES_LIST                 1039
#define IDC_EXTENSIONSLIST              1039
#define IDC_TE_CMDEDIT                  1040
#define IDC_STYLE_SAVEPRESETBUTTON      1040
#define IDC_TE_FOLDEREDIT               1041
#define IDC_REPLACETEXT_LABEL           1042
#define IDC_TE_PARAMSEDIT               1042
#define IDC_BACKSLASH_CHECK             1043
#define IDC_TE_SHORTCUTEDIT             1043
#define IDC_FINDTYPE_LABEL              1043
#define IDC_TE_INFOLABEL                1044
#define IDC_FINDWHERE_LABEL             1044
#define IDC_TEXTTITLE                   1045
#define IDC_BACKSLASHES_CHECK           1045
#define IDC_VERSIONSTATIC               1046
#define IDC_SUBDIRS_CHECK               1046
#define IDC_TE_CAPTURECHECK             1047
#define IDC_SEARCHUP_CHECK              1047
#define IDC_OPT_INDENTGUIDESCHECK       1048
#define IDC_TE_FILTERCHECK              1048
#define IDC_OPT_USETABSCHECK            1049
#define IDC_CHECK1                      1051
#define IDC_OPT_LINENOSCHECK            1051
#define IDC_SMARTSTART_ENABLECHECK      1051
#define IDC_TE_CLEARCHECK               1051
#define IDC_OPT_NEWFILEONSTART          1051
#define IDC_CHECKONSTARTUP              1051
#define IDC_TE_SAVEALLCHECK             1052
#define IDC_COMBO1                      1053
#define IDC_NEW_SCHEMECOMBO             1053
#define IDC_TE_OUTPUTCOMBO              1053
#define IDC_MULTIINSTANCECHECK          1053
#define IDC_FILEPROP_LINEENDINGS        1053
#define IDC_FILEASSO_METHOD             1053
#define IDC_FOLDER_COMBO                1053
#define IDC_STYLE_PRESETLIST            1053
#define IDC_STYLE_PRESETCOMBO           1053
#define IDC_OPT_LECOMBO                 1054
#define IDC_FILEPROP_ENCODING           1054
#define IDC_OPT_SHOWTABSCHECK           1054
#define IDC_OPT_CPCOMBO                 1055
#define IDC_FILEPROP_SCHEME             1055
#define IDC_OPT_TABSBOTTOMCHECK         1055
#define IDC_PNSAVE_SAVEASSTATIC         1056
#define IDC_OPT_MAXCHECK                1056
#define IDC_OPT_CSCOMBO                 1056
#define IDC_PNSAVE_TYPECOMBO            1057
#define IDC_TE_BUILTIN                  1057
#define IDC_OPT_HIDEONETABCHECK         1057
#define IDC_OPT_MAXTABSONLY             1057
#define IDC_TE_ABOUTBUILTIN             1058
#define IDC_TE_CUSTOMPARSE              1059
#define IDC_TE_CUSTOMSTR                1060
#define IDC_TE_CUSTOMTEXT               1060
#define IDC_TE_CUSTOMINFO               1061
#define IDC_OPT_FULLPATHCHECK           1062
#define IDC_COMBO2                      1063
#define IDC_TE_SAVECOMBO                1063
#define IDC_EDIT2                       1064
#define IDC_OPT_MRUCOUNT                1064
#define IDC_MAGICFOLDER_FILEFILTER      1064
#define IDC_OPT_MRUTEXTLENGTH           1065
#define IDC_MAGICFOLDER_FOLDERFILTER    1065
#define IDC_OPT_LINELIGHTCHECK          1066
#define IDC_OPT_NOLLHELPRADIO           1067
#define IDC_OPT_LLHIGHLIGHTRADIO        1068
#define IDC_OPT_LLLINERADIO             1069
#define IDC_TE_HOTKEY                   1071
#define IDC_STATIC_TC                   1072
#define IDC_STYLE_CURCOLBUTTON          1073
#define IDC_STYLE_SELUSEFORE            1074
#define IDC_PSHELPER_BUTTON             1076
#define IDC_AFILES_LIST                 1077
#define IDC_AFILES_ADDBUTTON            1078
#define IDC_AFILES_EDITBUTTON           1079
#define IDC_AFILES_REMOVEBUTTON         1080
#define IDC_ABOUTIMAGE                  1081
#define IDC_TOPSTATIC                   1082
#define IDC_OPT_WORDWRAPCHECK           1083
#define IDC_FILEPROP_LINES              1085
#define IDC_FILEPROP_CHARS              1086
#define IDC_FILEPROP_WORDS              1087
#define IDC_FILEPROP_FILENAME           1088
#define IDC_REOPEN_SWITCH               1089
#define IDC_REOPEN_DOIT                 1090
#define IDC_REOPEN_ASKME                1091
#define IDC_REDROP_SWITCH               1092
#define IDC_OPTHELPER_BUTTON            1092
#define IDC_REDROP_DOIT                 1093
#define IDC_REDROP_ASKME                1094
#define IDC_TAB1                        1096
#define IDC_SHELLTREE                   1097
#define IDC_NAME                        1098
#define IDC_CHECKNOW                    1099
#define IDC_PNOPEN_ENCODINGCOMBO        1100
#define IDC_PNOPEN_ENCODINGASSTATIC     1101
#define IDC_PNOPEN_ENCODINGSTATIC       1101
#define IDC_FINDEX_TABDUMMY             1102
#define IDC_FINDEX_TABS                 1103
#define IDC_FINDEX_LINE                 1104
#define IDC_CURRENTDOC_RADIO            1106
#define IDC_ALLOPEN_RADIO               1107
#define IDC_CURRENTPROJ_RADIO           1108
#define IDC_RADIO4                      1109
#define IDC_INSELECTION_RADIO           1109
#define IDC_FINDTEXT_LABEL              1110
#define IDC_SEARCHIN_GROUP              1111
#define IDC_FINDEXTABS_PLACEHOLDER      1112
#define IDC_OPENCURFILEDIRCHECK         1114
#define IDC_CLOSEONFINDNEXTCHECK        1115
#define IDC_FINDALPHACHECK              1116
#define IDC_TREE1                       1117
#define IDC_VAR_LIST                    1118
#define IDC_TE_CLICKRESULTSSTATIC       1120
#define IDC_TE_OUTPUTGROUP              1121
#define IDC_OPT_LINEENDINGSCHECK        1122
#define IDC_OPT_WHITESPACECHECK         1123
#define IDC_TAB_NOORRADIO               1124
#define IDC_TAB_FORCERADIO              1125
#define IDC_TAB_TABSRADIO               1125
#define IDC_TAB_SPACESRADIO             1126
#define IDC_OPT_TABORDERCHECK           1127
#define IDC_OPT_SAVEWORKSPACE           1128
#define IDC_FILETYPES_ADDBUTTON         1128
#define IDC_FILETYPES_EDITBUTTON        1129
#define IDC_FILETYPES_REMOVEBUTTON      1130
#define IDC_SCHEME_COMBO                1131
#define IDC_TE_TEXTFILTERCHECK          1133
#define IDC_INCLUDEHIDDEN_CHECK         1134
#define IDC_KB_ASSIGNEDLIST             1135
#define IDC_KB_HOTKEY                   1136
#define IDC_KB_SHORTCUTINUSE            1137
#define IDC_KB_SHORTCUTINUSELABEL       1137
#define IDC_ENABLEAUTOCOMPLETECHECK     1138
#define IDC_AUTOCOMPLETEKEYWORDSCHECK   1139
#define IDC_AUTOCOMPLETETAGSCHECK       1140
#define IDC_AUTOCLOSETAGSCHECK          1141
#define IDC_AUTOCLOSEBRACESCHECK        1142
#define IDC_NKEYSRADIO                  1143
#define IDC_MANUALRADIO                 1144
#define IDC_LINEHIGHLIGHTSLIDER         1145
#define IDC_OPT_FOLDINGCHECK            1146
#define IDC_CLIPLIST                    1147
#define IDC_CLIPS_ADDBUTTON             1148
#define IDC_CLIPS_EDITBUTTON            1149
#define IDC_CLIPS_REMOVEBUTTON          1150
#define IDC_OPT_LINELIGHTALPHACHECK     1152
#define IDC_MARKALL_BUTTON              21199
#define IDC_SEARCHALL_CHECK             21200
#define IDC_REHELPER_BUTTON             21204
#define IDC_RHELPER_BUTTON              21205
#define IDC_PSHELPER2_BUTTON            21205
#define IDC_BROWSE_BUTTON               21206
#define IDC_DIRECTION_GROUP             21207
#define IDC_FINDCOMBO                   21208
#define IDI_INFOICON                    32516
#define ID_VIEW_FIRSTDOCKER             32700
#define ID_VIEW_OUTPUT                  32700
#define ID_VIEW_WINDOWS_PROJECT         32701
#define ID_VIEW_WINDOWS_TEXTCLIPS       32702
#define ID_VIEW_WINDOWS_CTAGS           32703
#define ID_VIEW_WINDOWS_FINDRESULTS     32704
#define ID_VIEW_WINDOWS_SCRIPTS         32705
#define ID_VIEW_WINDOWS_BROWSER         32706
#define ID_VIEW_WINDOWS_OPENFILES       32707
#define ID_VIEW_LASTDOCKER              32707
#define IDS_PROJCLOSEFILES              32708
#define IDS_OPENANOTHER                 32709
#define IDS_TASKDLG_OK                  32710
#define IDS_TASKDLG_YES                 32711
#define IDS_TASKDLG_NO                  32712
#define IDS_TASKDLG_RETRY               32713
#define IDS_TASKDLG_CANCEL              32714
#define IDS_TASKDLG_CLOSE               32715
#define ID_EDIT_FINDNEXT                32773
#define ID_EDIT_GOTO                    32774
#define ID_TOOLS_LECRLF                 32777
#define ID_TOOLS_LELF                   32778
#define ID_TOOLS_LECR                   32779
#define ID_TOOLS_LECONVERT              32780
#define ID_BUTTON32781                  32781
#define ID_BOOKMARKS_NUMBERED_SET       32783
#define ID_BOOKMARKS_NUMBERED_JUMP      32784
#define ID_BOOKMARKS_TOGGLE             32786
#define ID_BOOKMARKS_NEXT               32787
#define ID_TOOLS_DUMMY                  32788
#define ID_TOOLS_STOPTOOLS              32789
#define ID_RECENTFILES_BLANKER          32790
#define ID_EDITOR_WHITESPACE            32791
#define ID_EDITOR_EOLCHARS              32792
#define ID_ACCELERATOR32794             32794
#define ID_VIEW_VIEWTABS                32825
#define ID_TAB_CLOSE                    32835
#define ID_VIEW_TABS_TOP                32836
#define ID_VIEW_TABS_BOTTOM             32837
#define ID_REGEXP_ANYCHARACTER          32839
#define ID_REGEXP_CHARACTERINRANGE      32840
#define ID_REGEXP_CHARACTERNOTINRANGE   32841
#define ID_REGEXP_BEGINNINGOFLINE       32842
#define ID_REGEXP_ENDOFLINE             32843
#define ID_REGEXP_TAGGEDEXPRESSSION     32844
#define ID_REGEXP_NOT                   32845
#define ID_REGEXP_OR                    32846
#define ID_REGEXP_0ORMOREMATCHES        32847
#define ID_REGEXP_1ORMOREMATCHES        32848
#define ID_REGEXP_GROUP                 32849
#define ID_EDIT_DELETE                  32862
#define ID_EDIT_INDENT                  32863
#define ID_EDIT_UNINDENT                32864
#define ID_FILE_SAVEALL                 32865
#define ID_EDIT_HEADERSWITCH            32866
#define ID_EDIT_COPYRTF                 32871
#define ID_PLACEHOLDER_SCHEMECOMBO      32873
#define ID_EDIT_FINDINFILES             32874
#define ID_PLACEHOLDER_FINDCOMBO        32875
#define ID_FINDTYPE_BUTTON              32876
#define ID_EXPORT_HTML                  32878
#define ID_HEADERFOOTERFIELDS_FILENAME  32879
#define ID_HEADERFOOTERFIELDS_FILEPATH  32880
#define ID_HEADERFOOTERFIELDS_CURRENTPAGE 32881
#define ID_HEADERFOOTERFIELDS_FILEDATE  32882
#define ID_HEADERFOOTERFIELDS_CURRENTDATE 32884
#define ID_HEADERFOOTERFIELDS_USERNAME  32886
#define ID_HEADERFOOTERFIELDS_FILETIME  32887
#define ID_HEADERFOOTERFIELDS_CURRENTTIME 32888
#define ID_FILE_ENCODING                32889
#define ID_ENCODING_8                   32890
#define ID_ENCODING_UTF16BE             32891
#define ID_ENCODING_UTF16LE             32892
#define ID_ENCODING_UTF8                32893
#define ID_ENCODING_UTF8NOBOM           32894
#define ID_PROJECT_SETACTIVEPROJECT     32897
#define ID_BUTTON32901                  32901
#define ID_VIEW_FILEPROPERTIES          32902
#define ID_EDIT_JUMPTO                  32905
#define ID_EDIT_DUPLICATELINE           32908
#define ID_EDIT_DELETELINE              32909
#define ID_EDIT_CUTLINE                 32910
#define ID_EDIT_UPPERCASE               32911
#define ID_EDIT_LOWERCASE               32912
#define ID_EDIT_TRANSPOSELINES          32913
#define ID_EDIT_COPYLINE                32914
#define ID_PROJECT_SORTFOLDERS          32916
#define ID_PROJECT_ADDMAGICFOLDER       32917
#define ID_PROJECT_MAGICADDFOLDER       32918
#define ID_FILE_CLOSEALL                32920
#define ID_PROJECT_PROPERTIES           32924
#define ID_WINDOW_CLOSEALLOTHER         32931
#define ID_DUMMY_ADDTOPROJECT           32938
#define ID_PROJECT_ADDTHISFILE          32939
#define ID_HELP_CONTENTS                32943
#define ID_PROJECT_SAVEPROJECT          32946
#define ID_PROJECT_REFRESH              32947
#define ID_EDIT_GOTOBRACE               32948
#define ID_FILE_SAVEWORKSPACEAS         32950
#define ID_EDIT_QUICKFIND               32953
#define ID_EDIT_FINDPREVIOUS            32956
#define ID_EDITOR_USEASSCRIPT           32960
#define ID_CTAGS_COLLAPSALL             32962
#define ID_CTAGS_EXPANDALL              32963
#define ID_PROJECT_MAGICADDFILE         32963
#define ID_EDIT_COMMENTS                32964
#define ID_COMMENTS_STREAM              32966
#define ID_COMMENTS_BLOCK               32967
#define ID_COMMENTS_LINE                32968
#define ID_COMMENTS_UNCOMMENT           32969
#define ID_EDIT_AUTOCOMPLETE            32970
#define ID_TOOLS_CONVERTTABSTOSPACES    32971
#define ID_TOOLS_CONVERTSPACESTOTABS    32972
#define ID_DUMMY_COPYFILEPATH           32973
#define ID_EDIT_COPYFILEPATH            32974
#define ID_DUMMY_OPENCONTAININGFOLDER   32975
#define ID_FILE_OPENCONTAININGFOLDER    32976
#define ID_PROJECT_OPENFOLDER           32977
#define ID_DUMMY_SHELLOPEN              32978
#define ID_PROJECT_SHELLOPEN            32979
#define ID_DUMMY_SHELLOPEN32980         32980
#define ID_FILE_SHELLOPEN               32981
#define ID_PROJECT_RENAME               32982
#define ID_DUMMY_RENAME                 32983
#define ID_DUMMY_RENAME32984            32984
#define ID_PROJECT_RENAME32985          32985
#define ID_WORKSPACE_RENAME             32986
#define ID_EDIT_INSERTCLIP              32987
#define ID_HELP_ONLINEHELP              32988
#define ID_HELP_WEB_DOCS                32989
#define ID_DUMMY_GOTODEFINITION         32990
#define ID_GO_TO_DEF                    32991
#define ID_EDITOR_GOTODEFINITION        32992
#define IDS_PROJECTDOESNOTEXIST         32993
#define ID_EDIT_FINDINFILES32994        32994
#define ID_WINDOWS_FILEBROWSER          32995
#define IDS_PROJSAVECHANGES             32996
#define ID_WINDOWS_OPENFILES            32997
#define ID_VIEW_PREVIOUSBOOKMARK        32998
#define ID_BOOKMARKS_PREVIOUS           32999
#define ID_HELP_FORUMS                  33000
#define ID_HELP_WEB_FORUMS              33001
#define ID_EDIT_LINE                    33002
#define ID_LINE_MOVELINEUP              33003
#define ID_EDIT_MOVELINEUP              33004
#define ID_LINE_MOVELINEDOWN            33005
#define ID_EDIT_MOVELINEDOWN            33006
#define ID_EDITOR_WRITEPROTECT          33107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        362
#define _APS_NEXT_COMMAND_VALUE         33108
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
