//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pn.rc
//
#define IDC_REPLACE_BUTTON              4
#define IDR_TBR_EDIT                    5
#define IDC_REPLACEALL_BUTTON           6
#define IDC_REPLACEINSEL_BUTTON         7
#define IDD_PAGESETUP                   12
#define IDC_HEADERTEXT                  30
#define IDC_FOOTERTEXT                  31
#define ID_MRUFILE_BASE                 50
#define IDD_ABOUTBOX                    100
#define IDC_FINDTEXT_COMBO              102
#define IDC_FINDNEXT_BUTTON             103
#define IDC_MATCHWHOLE_CHECK            104
#define IDC_MATCHCASE_CHECK             105
#define IDC_REPLACETEXT_COMBO           106
#define IDC_REGEXP_CHECK                107
#define IDC_UP_RADIO                    113
#define IDC_DOWN_RADIO                  114
#define ID_POS_PANE                     115
#define ID_MOD_PANE                     116
#define ID_INS_PANE                     117
#define IDR_MAINFRAME                   128
#define IDR_MDICHILD                    129
#define ID_EDITOR_WORDWRAP              130
#define ID_EDITOR_COLOURISE             131
#define ID_EDITOR_LINENOS               132
#define ID_EDITOR_OUTPUTWND             133
#define IDS_ABOUTVERSIONSTRING          133
#define IDS_TOOLFORMATSTRINGS           134
#define IDS_PATTERNFORMATSTRINGS        135
#define ID_FILE_NEW_PROJECT             136
#define ID_FILE_NEW_WORKSPACE           137
#define IDI_TEXTCLIPS                   167
#define IDD_FIND                        168
#define IDR_TABS_POPUP                  169
#define IDR_POPUP_REGEXP                170
#define IDD_REPLACE                     171
#define IDR_POPUP_EDITOR                173
#define IDB_EDITOR                      203
#define IDD_GOTO                        204
#define IDD_INPUTBOX                    204
#define ID_VIEW_CHANGESCHEME            221
#define ID_VIEW_SCHEMES                 222
#define IDR_POPUP_REGEXPM               226
#define ID_REGEXP_TAGGEDEXPRESSION1     227
#define ID_REGEXP_TAGGEDEXPRESSION2     228
#define ID_REGEXP_TAGGEDEXPRESSION3     229
#define ID_REGEXP_TAGGEDEXPRESSION4     230
#define ID_REGEXP_TAGGEDEXPRESSION5     231
#define ID_REGEXP_TAGGEDEXPRESSION6     232
#define ID_REGEXP_TAGGEDEXPRESSION7     233
#define ID_REGEXP_TAGGEDEXPRESSION8     234
#define ID_REGEXP_TAGGEDEXPRESSION9     235
#define ID_VIEW_TOOLBARS                236
#define ID_TOOLBARS_TOOLBAR             237
#define ID_VIEW_TOOLBAR_EDIT            238
#define ID_VIEW_LINENUMBERS             240
#define ID_VIEW_SYNTAXHIGHLIGHTING      241
#define ID_VIEW_WORDWRAP                242
#define IDD_OPTIONS                     243
#define IDD_TESTPAGE                    244
#define IDD_PAGE_STYLE                  244
#define ID_TOOLS_OPTIONS                245
#define ID_TOOLS_OPTIONS246             246
#define IDB_TRUETYPE_FONTTYPE           248
#define IDD_TAB_STYLES                  250
#define ID_HELP_WEB_PN                  251
#define ID_HELP_WEB_SF                  252
#define ID_HELP_WEB_SB                  253
#define ID_HELP_REPORTABUG              254
#define IDD_TOOLEDITOR                  255
#define ID_VIEW_OUTPUT                  256
#define IDR_POPUP_OUTPUT                257
#define ID_PROJECT_DELETE               258
#define ID_OUTPUT_CLEAR                 259
#define ID_OUTPUT_HIDE                  260
#define ID_TOOLS_USETABS                261
#define IDD_SMARTSTARTEDITOR            262
#define ID_FILE_REVERT                  263
#define ID_VIEW_INDIVIDUALOUTPUT        264
#define ID_FILE_EXPORT                  265
#define ID_EXPORT_RTF                   266
#define ID_EDIT_CLIPBOARDSWAP           267
#define ID_VIEW_COLLAPSEALLFOLDS        268
#define ID_VIEW_EXPANDALLFOLDS          269
#define ID_VIEW_FOLDING                 270
#define ID_COLLAPSEALLFOLDS_TOGGLEFOLD  271
#define ID_VIEW_TOGGLEFOLD              272
#define ID_EDIT_SELECTALL               273
#define ID_HELP_WEB_SR                  275
#define IDR_TBR_SCHEME                  276
#define IDR_TOOLBAR1                    278
#define IDR_TBR_FINDCOMBO               278
#define IDR_TBR_FIND                    278
#define IDB_FINDTOOLBAR                 280
#define IDR_FINDBAR_DDMENU              281
#define IDR_POPUP_FINDBARDD             281
#define ID_FINDBAR_SEARCHGOOGLE         282
#define ID_FINDBAR_SEARCHGOOGLEGROUPS   283
#define IDI_ICON1                       284
#define IDR_MENU1                       285
#define IDR_POPUP_PROJECTFILE           285
#define ID_PROJECT_REMOVE               286
#define ID_PROJECT_OPEN                 287
#define ID_PROJECT_ADDFILES             288
#define ID_FILE_OPENPROJECT             289
#define IDR_POPUP_PROJECTFOLDER         290
#define ID_DUMMY_ADDFILES               291
#define ID_DUMMY_DELETE                 292
#define ID_PROJECT_ADDFOLDER            293
#define IDR_POPUP_PROJECT               294
#define ID_DUMMY_ADDFILES295            295
#define ID_DUMMY_ADDFOLDER              296
#define ID_PROJECT_REMOVEPROJECT        297
#define ID_PROJECT_DELETEPROJECT        298
#define ID_PROJECT_OPENALLFILES         299
#define IDI_ICON2                       300
#define IDI_PROJECTS                    300
#define ID_FILE_CLOSEWORKSPACE          301
#define ID_VIEW_TOOLBARS_FIND           302
#define ID_VIEW_TOOLBARS_SCHEMES        303
#define ID_VIEW_WINDOWS                 304
#define ID_VIEW_WINDOWS_PROJECT         305
#define ID_VIEW_WINDOWS_TEXTCLIPS       306
#define IDR_POPUP_WORKSPACE             307
#define ID_WORKSPACE_NEWPROJECT         308
#define ID_WORKSPACE_ADDPROJECT         309
#define IDI_PROJECTFOLDER               310
#define IDI_WORKSPACE                   311
#define IDI_ICON3                       312
#define IDI_BADPROJECT                  312
#define IDD_PNSAVE                      423
#define IDD_PAGE_SCHEMES                424
#define IDD_TAB_STYLES1                 425
#define IDD_TAB_KEYWORDS                425
#define IDD_PAGE_TOOLS                  426
#define IDD_PAGE_GENERAL                427
#define IDD_PAGE_SMARTSTART             428
#define IDD_PAGE_NEWFILES               428
#define IDD_PAGE_VISUALHELP             429
#define IDD_TAB_MISC                    430
#define IDC_FINDTEXT_DUMMY              1001
#define IDC_REPLACETEXT_DUMMY           1002
#define IDC_GOTOEDIT                    1004
#define IDC_THEEDIT                     1004
#define IDC_PNSCOMBO                    1005
#define IDC_HELPBTN                     1006
#define IDC_TREE                        1007
#define IDC_PLACEHOLDER                 1008
#define IDC_PROGRESS1                   1009
#define IDC_BUTTON1                     1010
#define IDC_STYLE_FOREBUTTON            1010
#define IDC_TOOLS_ADDBUTTON             1010
#define IDC_TE_COMMANDBUTTON            1010
#define IDC_SMARTSTART_REMOVE           1010
#define IDC_SMARTSTART_REMOVEBUTTON     1010
#define IDC_OPT_LINELIGHTBUTTON         1010
#define IDC_EDIT1                       1011
#define IDC_KEYWORDS_KEYWORDTEXT        1011
#define IDC_TOOLS_EDITBUTTON            1011
#define IDC_TE_NAMEEDIT                 1011
#define IDC_OPT_TABWIDTHEDIT            1011
#define IDC_PHRASEEDIT                  1011
#define IDC_OPT_LLCOLUMNEDIT            1011
#define IDC_STYLE_SELFOREBUTTON         1011
#define IDC_FONT_COMBO                  1012
#define IDC_TOOLS_REMOVEBUTTON          1012
#define IDC_TE_BROWSEBUTTON             1012
#define IDC_TE_DIRBUTTON                1012
#define IDC_STYLE_SELBACKBUTTON         1012
#define IDC_FONTSIZE_COMBO              1013
#define IDC_STYLE_IGCOLBUTTON           1013
#define IDC_SCHEMECOMBO                 1016
#define IDC_SCHEMELABEL                 1017
#define IDC_STYLES_TREE                 1020
#define IDC_STYLE_BOLDCHECK             1021
#define IDC_STYLE_ITALICCHECK           1022
#define IDC_STYLE_UNDERLINECHECK        1023
#define IDC_STYLE_EOLFILLEDCHECK        1024
#define IDC_STYLE_EXAMPLE               1027
#define IDC_PS_PLACEHOLDER              1029
#define IDC_STYLE_FONTCOMBO             1031
#define IDC_STYLE_SIZECOMBO             1032
#define IDC_BUTTON2                     1033
#define IDC_STYLE_BACKBUTTON            1033
#define IDC_KEYWORDS_RESETBUTTON        1033
#define IDC_TOOLS_MOVEUPBUTTON          1033
#define IDC_TE_CLEARBUTTON              1033
#define IDC_SMARTSTART_EDITBUTTON       1033
#define IDC_OPT_LLCOLORBUTTON           1033
#define IDC_KEYWORDS_SORTBUTTON         1034
#define IDC_TOOLS_MOVEDOWNBUTTON        1034
#define IDC_SMARTSTART_ADDBUTTON        1034
#define IDC_STYLE_RESETBTN              1036
#define IDC_STYLE_RESETALLBTN           1037
#define IDC_LIST1                       1039
#define IDC_KEYWORDS_LIST               1039
#define IDC_LIST                        1039
#define IDC_SMARTSTART_LIST             1039
#define IDC_TE_CMDEDIT                  1040
#define IDC_TE_FOLDEREDIT               1041
#define IDC_REPLACETEXT_LABEL           1042
#define IDC_TE_PARAMSEDIT               1042
#define IDC_BACKSLASH_CHECK             1043
#define IDC_TE_SHORTCUTEDIT             1043
#define IDC_TE_INFOLABEL                1044
#define IDC_TEXTTITLE                   1045
#define IDC_VERSIONSTATIC               1046
#define IDC_TE_CAPTURECHECK             1047
#define IDC_OPT_INDENTGUIDESCHECK       1048
#define IDC_TE_FILTERCHECK              1048
#define IDC_OPT_USETABSCHECK            1049
#define IDC_CHECK1                      1051
#define IDC_OPT_LINENOSCHECK            1051
#define IDC_SMARTSTART_ENABLECHECK      1051
#define IDC_TE_CLEARCHECK               1051
#define IDC_TE_SAVEALLCHECK             1052
#define IDC_COMBO1                      1053
#define IDC_NEW_SCHEMECOMBO             1053
#define IDC_TE_OUTPUTCOMBO              1053
#define IDC_MULTIINSTANCECHECK          1053
#define IDC_OPT_LECOMBO                 1054
#define IDC_PNSAVE_SAVEASSTATIC         1056
#define IDC_OPT_MAXCHECK                1056
#define IDC_PNSAVE_TYPECOMBO            1057
#define IDC_TE_BUILTIN                  1057
#define IDC_TE_ABOUTBUILTIN             1058
#define IDC_TE_CUSTOMPARSE              1059
#define IDC_TE_CUSTOMSTR                1060
#define IDC_TE_CUSTOMTEXT               1060
#define IDC_TE_CUSTOMINFO               1061
#define IDC_OPT_FULLPATHCHECK           1062
#define IDC_COMBO2                      1063
#define IDC_TE_SAVECOMBO                1063
#define IDC_EDIT2                       1064
#define IDC_OPT_MRUCOUNT                1064
#define IDC_OPT_MRUTEXTLENGTH           1065
#define IDC_OPT_LINELIGHTCHECK          1066
#define IDC_OPT_NOLLHELPRADIO           1067
#define IDC_OPT_LLHIGHLIGHTRADIO        1068
#define IDC_OPT_LLLINERADIO             1069
#define IDC_TE_HOTKEY                   1071
#define IDC_STATIC_TC                   1072
#define IDC_STYLE_CURCOLBUTTON          1073
#define IDC_STYLE_SELUSEFORE            1074
#define IDC_CHECK2                      1075
#define IDC_MARKALL_BUTTON              21199
#define IDC_SEARCHALL_CHECK             21200
#define IDC_REHELPER_BUTTON             21204
#define IDC_RHELPER_BUTTON              21205
#define IDC_DIRECTION_GROUP             21207
#define IDC_FINDCOMBO                   21208
#define ID_EDIT_FINDNEXT                32773
#define ID_EDIT_GOTO                    32774
#define ID_TOOLS_LECRLF                 32777
#define ID_TOOLS_LELF                   32778
#define ID_TOOLS_LECR                   32779
#define ID_TOOLS_LECONVERT              32780
#define ID_BUTTON32781                  32781
#define ID_BOOKMARKS_NUMBERED_SET       32783
#define ID_BOOKMARKS_NUMBERED_JUMP      32784
#define ID_BOOKMARKS_TOGGLE             32786
#define ID_BOOKMARKS_NEXT               32787
#define ID_TOOLS_DUMMY                  32788
#define ID_TOOLS_STOPTOOLS              32789
#define ID_RECENTFILES_BLANKER          32790
#define ID_EDITOR_WHITESPACE            32791
#define ID_EDITOR_EOLCHARS              32792
#define ID_ACCELERATOR32794             32794
#define ID_VIEW_VIEWTABS                32825
#define ID_TAB_CLOSE                    32835
#define ID_VIEW_TABS_TOP                32836
#define ID_VIEW_TABS_BOTTOM             32837
#define ID_REGEXP_ANYCHARACTER          32839
#define ID_REGEXP_CHARACTERINRANGE      32840
#define ID_REGEXP_CHARACTERNOTINRANGE   32841
#define ID_REGEXP_BEGINNINGOFLINE       32842
#define ID_REGEXP_ENDOFLINE             32843
#define ID_REGEXP_TAGGEDEXPRESSSION     32844
#define ID_REGEXP_NOT                   32845
#define ID_REGEXP_OR                    32846
#define ID_REGEXP_0ORMOREMATCHES        32847
#define ID_REGEXP_1ORMOREMATCHES        32848
#define ID_REGEXP_GROUP                 32849
#define ID_EDIT_DELETE                  32862
#define ID_EDIT_INDENT                  32863
#define ID_EDIT_UNINDENT                32864
#define ID_FILE_SAVEALL                 32865
#define ID_EDIT_HEADERSWITCH            32866
#define ID_EDIT_COPYRTF                 32871
#define ID_PLACEHOLDER_SCHEMECOMBO      32873
#define ID_EDIT_FINDINFILES             32874
#define ID_PLACEHOLDER_FINDCOMBO        32875
#define ID_FINDTYPE_BUTTON              32876
#define ID_EXPORT_HTML                  32878
#define IDC_FINDTEXT_LABEL              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        314
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
