#define PN_MAJOR			2
#define PN_MINOR			4
#define PN_REVISION			2
#ifndef PN_BUILD
	#define PN_BUILD		0
#endif

#define PN_VERSION_STRINGIZE_(s) #s
#define PN_VERSION_STRINGIZE(s) PN_VERSION_STRINGIZE_(s)

#define PN_VERSTRING		PN_VERSION_STRINGIZE(PN_MAJOR) "." PN_VERSION_STRINGIZE(PN_MINOR) "." PN_VERSION_STRINGIZE(PN_REVISION) "." PN_VERSION_STRINGIZE(PN_BUILD)
#define PN_VERSTRING_T		_T(PN_VERSION_STRINGIZE(PN_MAJOR)) _T(".") _T(PN_VERSION_STRINGIZE(PN_MINOR)) _T(".") _T(PN_VERSION_STRINGIZE(PN_REVISION)) _T(".") _T(PN_VERSION_STRINGIZE(PN_BUILD))

#ifndef PN_VERNAME
	#define PN_VERNAME			"-duke"
#endif

#define PN_VIVERSION		PN_MAJOR,PN_MINOR,0,0
#define PN_VIVERSION_FILE	PN_MAJOR,PN_MINOR,PN_REVISION,PN_BUILD
#define PN_VERSION			PN_VERSTRING
#define PN_VERSION_FULL		PN_VERSTRING PN_VERNAME
#define PN_VERSION_FULL_T	PN_VERSTRING_T _T(PN_VERNAME)
